package mhir.parse

import mhir.ir._

/** Parser for [[https://dl.acm.org/doi/10.1145/3385412.3385983 Aetherling]].
  */
object AetherlingParser {

  /** Parse a program from Aetherling's space-time language to an
    * [[mhir.ir.Expr]].
    *
    * ==Grammar==
    * The program must be generated by the following grammar:
    * {{{
    *   prog       ::= (module "\n\n")* module
    *   module     ::= ident param+ " =" ("\n" assignment)+
    *   param      ::= " (" ident " :: " typ ")"
    *   typ        ::= "BitT"
    *                | "UInt8T"
    *                | "UInt32T"
    *                | "(ATupleT " typ " " typ ")"
    *                | "(SSeqT " nat " " typ ")"
    *                | "(TSeqT " nat " " nat " " typ ")"
    *   assignment ::= ident " = " expr
    *   expr       ::= "(" expr ")"
    *                | ident
    *                | quot_ident
    *                | "AddN " typ " " expr
    *                | "Const_GenN " const " " nat " " typ
    *                | "ATupleN " typ " " typ " " expr " " expr
    *                | "FIFON " typ " " nat " " expr
    *                | "Map_tN " nat " " nat " " expr " " expr
    *                | "Map_sN " nat " " expr " " expr
    *                | ... (TODO)
    *   const      ::= "UInt8V " nat
    *                | "UInt32V " nat
    *                | ... (TODO)
    *   ident      ::= letter (letter | digit)*
    *   quot_ident ::= "\"" ident "\""
    *   nat        ::= digit+
    * }}}
    *
    * @param code
    *   an Atherling program.
    * @throws SyntaxError
    *   if the program is syntactically invalid.
    */
  def parse(code: String): Expr = {
    val modules = code.split("\n\n").map(x => x.strip())
    val moduleDecls = modules.foldLeft(Map[Param, Function]())({
      case (modByName, code) =>
        val (name, func) = parseModule(code, modByName)
        modByName + (name -> func)
    })
    Lets(moduleDecls.toSeq.init: _*)(moduleDecls.last._1)
  }

  private def parseModule(
      code: String,
      moduleByName: Map[Param, Function]
  ): (Param, Expr) = {
    val lines = code.linesIterator.toSeq
    val (funcName, inputName) = parseModuleSignature(lines.head)
    val assignments = lines.tail.foldLeft(Map[Param, Expr]())({
      case (acc, line) =>
        val (x, v) = parseAssignment(line)
        acc + (x -> v)
    })
    (
      funcName,
      Function(
        inputName,
        Lets(assignments.toSeq.init: _*)(assignments.last._2)
      )()
    )
  }

  private def parseModuleSignature(sig: String): (Param, Param) = {
    ???
  }

  private def parseAssignment(line: String): (Param, Expr) = {
    ???
  }
}
