package mhir.parse

import mhir.ir._
import mhir.sugar.{Fifo, StmMap, VecMap}

import scala.annotation.tailrec
import scala.collection.immutable.ListMap

/** Parser for [[https://dl.acm.org/doi/10.1145/3385412.3385983 Aetherling]]'s
  * space-time language.
  */
object AetherlingParser {

  /** Parse a program from Aetherling's space-time language to an
    * [[mhir.ir.Expr]].
    *
    * ==Grammar==
    * The program must be generated by the following grammar:
    * {{{
    *   prog       ::= module+
    *   module     ::= ident param+ " =" assignment+ "\n\n"
    *   param      ::= " (" ident " :: " typ ")"
    *   typ        ::= "BitT"
    *                | "UInt8T"
    *                | "UInt32T"
    *                | "(ATupleT " typ " " typ ")"
    *                | "(SSeqT " nat " " typ ")"
    *                | "(TSeqT " nat " " nat " " typ ")"
    *   assignment ::= "\n    " ident " = " expr
    *   expr       ::= "(" expr ")"
    *                | ident
    *                | quot_ident
    *                // ----- basic operators
    *                | "IdN " expr
    *                | "AbsN " typ " " expr
    *                | "NotN " expr
    *                | "AndN " expr
    *                | "OrN " expr
    *                | "AddN " typ " " expr
    *                | "SubN " typ " " expr
    *                | "MulN " typ " " expr
    *                | "DivN " typ " " expr
    *                | "LSRN " typ " " expr
    *                | "LSLN " typ " " expr
    *                | "LtN " typ " " expr
    *                | "EqN " typ " " expr
    *                | "IfN " typ " " expr
    *                // ----- generators
    *                | "Lut_GenN " ???
    *                | "Const_GenN " const " " nat " " typ
    *                | "Counter_sN " nat " " nat " " typ " " nat
    *                | "Counter_tN " nat " " nat " " nat " " typ " " nat
    *                | "Counter_tsN " nat " " nat " " nat " " nat " " typ " " nat
    *                | "Counter_tnN " nat_list " " nat_list " " nat " " typ " " nat
    *                // ----- sequence operators
    *                | "Shift_sN " nat " " nat " " typ " " expr
    *                | "Shift_tN " nat " " nat " " nat " " typ " " expr
    *                | "Shift_tsN " nat " " nat " " nat " " nat " " typ " " expr
    *                | "Shift_ttN " nat " " nat " " nat " " nat " " nat " " typ " " expr
    *                | "Shift_tnN " nat " " nat_list " " nat " " nat_list " " nat " " typ " " expr
    *                | "Up_1d_sN " nat " " typ " " expr
    *                | "Up_1d_tN " nat " " nat " " typ " " expr
    *                | "Down_1d_sN " nat " " nat " " typ " " expr
    *                | "Down_1d_tN " nat " " nat " " nat " " typ " " expr
    *                | "Partition_s_ssN " nat " " nat " " typ " " expr
    *                | "Partition_t_ttN " nat " " nat " " nat " " nat " " typ " " expr
    *                | "Unpartition_s_ssN " nat " " nat " " typ " " expr
    *                | "Unpartition_t_ttN " nat " " nat " " nat " " nat " " typ " " expr
    *                | "SerializeN " nat " " nat " " typ " " expr
    *                | "DeserializeN " nat " " nat " " typ " " expr
    *                | "Add_1_sN " expr " " expr
    *                | "Add_1_0_tN " expr " " expr
    *                | "Remove_1_sN " expr " " expr
    *                | "Remove_1_0_tN " expr " " expr
    *                // ----- higher-order operators
    *                | "Map_sN " nat " " expr " " expr
    *                | "Map_tN " nat " " nat " " expr " " expr
    *                | "Map2_sN " nat " " expr " " expr " " expr
    *                | "Map2_tN " nat " " nat " " expr " " expr " " expr
    *                | "Reduce_sN " nat " " expr " " expr
    *                | "Reduce_tN " nat " " nat " " expr " " expr
    *                // ----- tuple operators
    *                | "FstN " typ " " typ " " expr
    *                | "SndN " typ " " typ " " expr
    *                | "ATupleN " typ " " typ " " expr " " expr
    *                | "STupleN " typ " " expr " " expr
    *                | "STupleAppendN " nat " " typ " " expr " " expr
    *                | "STupleToSSeqN " nat " " typ " " expr
    *                | "SSeqToSTupleN " nat " " typ " " expr
    *                // ----- miscellaneous
    *                | "InputN " ???
    *                | "ErrorN " ???
    *                | "FIFON " typ " " nat " " expr
    *                | "ReshapeN (" typ ") (" typ ")"
    *   const      ::= "UnitV"
    *                | "BitV " bool
    *                | "Int8V " nat
    *                | "UInt8V " nat
    *                | "FixP1_7V " float
    *                | "Int16V " nat
    *                | "UInt16V " nat
    *                | "Int32V " nat
    *                | "UInt32V " nat
    *                | "ATupleV " const " " const
    *                | "STupleV " const_list
    *                | "SSeqV " const_list
    *                | "TSeqV {vals = " const_list ", i_v = " nat "}"
    *   const_list ::= "[]"
    *                | "[" const ("," const)* "]"
    *   ident      ::= letter (letter | digit)*
    *   quot_ident ::= "\"" ident "\""
    *   nat        ::= digit+
    *   nat_list   ::= "[]"
    *                | "[" nat ("," nat)* "]"
    *   bool       ::= "True" | "False"
    * }}}
    *
    * @param code
    *   an Aetherling program.
    * @throws SyntaxError
    *   if the program is syntactically invalid.
    */
  def parse(code: String): Expr = {
    parseProgram(code, ListMap())
  }

  @tailrec
  private def parseProgram(
      code: String,
      modules: ListMap[Param, Function]
  ): Expr = {
    val (modName, modImpl, suffix) = parseModule(code, modules)
    if (suffix.isBlank) {
      Lets(modules.toSeq: _*)(modImpl)
    } else {
      parseProgram(suffix, modules + (modName -> modImpl))
    }
  }

  private def parseModule(
      code: String,
      modules: ListMap[Param, Function]
  ): (Param, Function, String) = {
    val (name, suffix0) = parseIdentifier(code)
    val (params, suffix1) = parseOneOrMoreParams(suffix0, Seq())
    val suffix2 = expect(suffix1, " =")
    val (assignments, suffix3) =
      parseOneOrMoreAssignments(suffix2, modules, ListMap())
    val suffix4 = expect(suffix3, "\n\n")
    val func = {
      val body = Lets(assignments.toSeq.init: _*)(assignments.last._2)
      val x0 = params.last
      val f0 = Function(x0, body)()
      params.init.foldRight(f0)({ case (x, body) => Function(x, body)() })
    }
    (name, func, suffix4)
  }

  private def parseIdentifier(code: String): (Param, String) = {
    if (code.isEmpty || !code.head.isLetter) {
      throw new SyntaxError(s"Expected an identifier but got $code")
    }
    val (name, suffix) = code.span(c => c.isLetterOrDigit)
    (Param(name, -1)(Missing), suffix)
  }

  private def parseQuotedIdentifier(code: String): (Param, String) = {
    val suffix0 = expect(code, "\"")
    val (x, suffix1) = parseIdentifier(suffix0)
    val suffix2 = expect(suffix1, "\"")
    (x, suffix2)
  }

  @tailrec
  private def parseOneOrMoreParams(
      code: String,
      params: Seq[Param]
  ): (Seq[Param], String) = {
    val (x, suffix) = parseParam(code)
    if (suffix.startsWith(" (")) {
      parseOneOrMoreParams(suffix, params :+ x)
    } else {
      (params :+ x, suffix)
    }
  }

  private def parseParam(code: String): (Param, String) = {
    val suffix0 = expect(code, " (")
    val (name, suffix1) = parseIdentifier(suffix0)
    val suffix2 = expect(suffix1, " :: ")
    val (typ, suffix3) = parseTyp(suffix2)
    val suffix4 = expect(suffix3, ")")
    (name.rebuild(typ).asInstanceOf[Param], suffix4)
  }

  @tailrec
  private def parseOneOrMoreAssignments(
      code: String,
      modules: ListMap[Param, Function],
      assignments: ListMap[Param, Expr]
  ): (ListMap[Param, Expr], String) = {
    val (x, v, suffix) = parseAssignment(code, modules)
    if (suffix.startsWith("\n    ")) {
      parseOneOrMoreAssignments(suffix, modules, assignments + (x -> v))
    } else {
      (assignments + (x -> v), suffix)
    }
  }

  private def parseAssignment(
      code: String,
      modules: ListMap[Param, Function]
  ): (Param, Expr, String) = {
    val suffix0 = expect(code, "\n    ")
    val (x, suffix1) = parseIdentifier(suffix0)
    val suffix2 = expect(suffix1, " = ")
    val (v, suffix3) = parseExpr(suffix2, modules)
    (x, v, suffix3)
  }

  private def parseTyp(code: String): (Type, String) = {
    if (code.startsWith("BitT")) {
      (TyBool, expect(code, "BitT"))
    } else if (code.startsWith("UInt8T")) {
      (U8, expect(code, "UInt8T"))
    } else if (code.startsWith("UInt32T")) {
      (U32, expect(code, "UInt32T"))
    } else if (code.startsWith("(ATupleT ")) {
      val suffix0 = expect(code, "(ATupleT ")
      val (t0, suffix1) = parseTyp(suffix0)
      val suffix2 = expect(suffix1, " ")
      val (t1, suffix3) = parseTyp(suffix2)
      val suffix4 = expect(suffix3, ")")
      (TyTuple(t0, t1), suffix4)
    } else if (code.startsWith("(SSeqT ")) {
      val suffix0 = expect(code, "(SSeqT ")
      val (n, suffix1) = parseNat(suffix0)
      val suffix2 = expect(suffix1, " ")
      val (t, suffix3) = parseTyp(suffix2)
      val suffix4 = expect(suffix3, ")")
      (TyVec(t, n), suffix4)
    } else if (code.startsWith("(TSeqT ")) {
      val suffix0 = expect(code, "(TSeqT ")
      val (n, suffix1) = parseNat(suffix0)
      val suffix2 = expect(suffix1, " ")
      val (_, suffix3) = parseNat(suffix2)
      val suffix4 = expect(suffix3, " ")
      val (t, suffix5) = parseTyp(suffix4)
      val suffix6 = expect(suffix5, ")")
      (TyStm(t, n), suffix6)
    } else {
      throw new SyntaxError(s"Expected a type but got $code")
    }
  }

  private def parseNat(code: String): (Int, String) = {
    val (nStr, suffix) = code.span(c => c.isDigit)
    if (nStr.isEmpty) {
      throw new SyntaxError(s"Expected a natural number but got $code")
    }
    val n = Integer.parseUnsignedInt(nStr)
    (n, suffix)
  }

  private def parseExpr(
      code: String,
      modules: ListMap[Param, Function]
  ): (Expr, String) = {
    if (code.startsWith("(")) {
      val suffix0 = expect(code, "(")
      val (e, suffix1) = parseExpr(suffix0, modules)
      val suffix2 = expect(suffix1, ")")
      (e, suffix2)
    } else if (code.startsWith("IdN ")) {
      ???
    } else if (code.startsWith("AbsN ")) {
      ???
    } else if (code.startsWith("NotN ")) {
      ???
    } else if (code.startsWith("AndN ")) {
      ???
    } else if (code.startsWith("OrN ")) {
      ???
    } else if (code.startsWith("AddN ")) {
      val suffix0 = expect(code, "AddN ")
      // TODO: Add a node like `AssertType` which is removed by the type
      //       checker?
      val (_, suffix1) = parseTyp(suffix0)
      val suffix2 = expect(suffix1, " ")
      val (e, suffix3) = parseExpr(suffix2, modules)
      (e.__0 + e.__1, suffix3)
    } else if (code.startsWith("SubN ")) {
      ???
    } else if (code.startsWith("MulN ")) {
      ???
    } else if (code.startsWith("DivN ")) {
      ???
    } else if (code.startsWith("LSRN ")) {
      ???
    } else if (code.startsWith("LSLN ")) {
      ???
    } else if (code.startsWith("LtN ")) {
      ???
    } else if (code.startsWith("EqN ")) {
      ???
    } else if (code.startsWith("IfN ")) {
      ???
    } else if (code.startsWith("Lut_GenN ")) {
      ???
    } else if (code.startsWith("Const_GenN ")) {
      val suffix0 = expect(code, "Const_GenN ")
      val (c, suffix1) = parseConst(suffix0)
      val suffix2 = expect(suffix1, " ")
      val (_, suffix3) = parseNat(suffix2)
      val suffix4 = expect(suffix3, " ")
      // TODO: Assert type?
      val (_, suffix5) = parseTyp(suffix4)
      (c, suffix5)
    } else if (code.startsWith("Counter_sN ")) {
      ???
    } else if (code.startsWith("Counter_tN ")) {
      ???
    } else if (code.startsWith("Counter_tsN ")) {
      ???
    } else if (code.startsWith("Counter_tnN ")) {
      ???
    } else if (code.startsWith("Shift_sN ")) {
      ???
    } else if (code.startsWith("Shift_tN ")) {
      ???
    } else if (code.startsWith("Shift_tsN ")) {
      ???
    } else if (code.startsWith("Shift_ttN ")) {
      ???
    } else if (code.startsWith("Shift_tnN ")) {
      ???
    } else if (code.startsWith("Up_1d_sN")) {
      ???
    } else if (code.startsWith("Up_1d_tN ")) {
      ???
    } else if (code.startsWith("Down_1d_sN ")) {
      ???
    } else if (code.startsWith("Down_1d_tN ")) {
      ???
    } else if (code.startsWith("Partition_s_ssN ")) {
      ???
    } else if (code.startsWith("Partition_t_ttN ")) {
      ???
    } else if (code.startsWith("Unpartition_s_ssN ")) {
      ???
    } else if (code.startsWith("Unpartition_t_ttN ")) {
      ???
    } else if (code.startsWith("SerializeN ")) {
      ???
    } else if (code.startsWith("DeserializeN ")) {
      ???
    } else if (code.startsWith("Add_1_sN ")) {
      ???
    } else if (code.startsWith("Add_1_0_tN")) {
      ???
    } else if (code.startsWith("Remove_1_sN ")) {
      ???
    } else if (code.startsWith("Remove_1_0_tN ")) {
      ???
    } else if (code.startsWith("Map_sN ")) {
      val suffix0 = expect(code, "Map_sN ")
      // TODO: Assert type?
      val (_, suffix1) = parseNat(suffix0)
      val suffix2 = expect(suffix1, " ")
      val (f, suffix3) = parseExpr(suffix2, modules)
      val suffix4 = expect(suffix3, " ")
      val (v, suffix5) = parseExpr(suffix4, modules)
      (VecMap(v, f)(), suffix5)
    } else if (code.startsWith("Map_tN ")) {
      val suffix0 = expect(code, "Map_tN ")
      val (_, suffix1) = parseNat(suffix0)
      val suffix2 = expect(suffix1, " ")
      val (_, suffix3) = parseNat(suffix2)
      val suffix4 = expect(suffix3, " ")
      val (f, suffix5) = parseExpr(suffix4, modules)
      val suffix6 = expect(suffix5, " ")
      val (s, suffix7) = parseExpr(suffix6, modules)
      // The function in StmMap must be a literal function
      val g: Function = f match {
        case x: Param if modules.contains(x) =>
          modules(x)
        case _ =>
          Function(Param("I", -1)(Missing), f)()
      }
      (StmMap(s, g)(), suffix7)
    } else if (code.startsWith("Map2_sN ")) {
      ???
    } else if (code.startsWith("Map2_tN ")) {
      ???
    } else if (code.startsWith("Reduce_sN ")) {
      ???
    } else if (code.startsWith("Reduce_tN ")) {
      ???
    } else if (code.startsWith("FstN ")) {
      ???
    } else if (code.startsWith("SndN ")) {
      ???
    } else if (code.startsWith("ATupleN ")) {
      // TODO: Assert type?
      val suffix0 = expect(code, "ATupleN ")
      val (_, suffix1) = parseTyp(suffix0)
      val suffix2 = expect(suffix1, " ")
      val (_, suffix3) = parseTyp(suffix2)
      val suffix4 = expect(suffix3, " ")
      val (e0, suffix5) = parseExpr(suffix4, modules)
      val suffix6 = expect(suffix5, " ")
      val (e1, suffix7) = parseExpr(suffix6, modules)
      (Tuple(e0, e1)(), suffix7)
    } else if (code.startsWith("STupleN ")) {
      ???
    } else if (code.startsWith("STupleAppendN ")) {
      ???
    } else if (code.startsWith("STupleToSSeqN ")) {
      ???
    } else if (code.startsWith("SSeqToSTupleN ")) {
      ???
    } else if (code.startsWith("InputN ")) {
      ???
    } else if (code.startsWith("ErrorN ")) {
      ???
    } else if (code.startsWith("FIFON ")) {
      val suffix0 = expect(code, "FIFON ")
      // TODO: Assert type?
      val (_, suffix1) = parseTyp(suffix0)
      val suffix2 = expect(suffix1, " ")
      val (_, suffix3) = parseNat(suffix2)
      val suffix4 = expect(suffix3, " ")
      val (e, suffix5) = parseExpr(suffix4, modules)
      (Fifo(e), suffix5)
    } else if (code.startsWith("ReshapeN ")) {
      ???
    } else if (code.startsWith("\"")) {
      parseQuotedIdentifier(code)
    } else if (code.head.isLetter) {
      parseIdentifier(code)
    } else {
      throw new SyntaxError(s"Expected an expression but got $code")
    }
  }

  private def parseConst(code: String): (Expr, String) = {
    if (code.startsWith("UnitV")) {
      ???
    } else if (code.startsWith("BitV ")) {
      ???
    } else if (code.startsWith("Int8V ")) {
      ???
    } else if (code.startsWith("UInt8V ")) {
      val suffix0 = expect(code, "UInt8V ")
      val (n, suffix1) = parseNat(suffix0)
      (C(n)(U8), suffix1)
    } else if (code.startsWith("FixP1_7V ")) {
      ???
    } else if (code.startsWith("Int16V ")) {
      ???
    } else if (code.startsWith("UInt16V ")) {
      ???
    } else if (code.startsWith("Int32V ")) {
      ???
    } else if (code.startsWith("UInt32V ")) {
      val suffix0 = expect(code, "UInt32V ")
      val (n, suffix1) = parseNat(suffix0)
      (C(n)(U32), suffix1)
    } else if (code.startsWith("ATupleV ")) {
      ???
    } else if (code.startsWith("STupleV ")) {
      ???
    } else if (code.startsWith("SSeqV ")) {
      ???
    } else if (code.startsWith("TSeqV ")) {
      ???
    } else {
      throw new SyntaxError(s"Expected a constant but got $code")
    }
  }

  private def expect(code: String, prefix: String): String = {
    if (!code.startsWith(prefix)) {
      throw new SyntaxError(s"Expected '$prefix' but got $code")
    }
    code.substring(prefix.length)
  }
}
