package mhir.parse

import mhir.ir._
import mhir.sugar.{Fifo, StmMap, VecMap}

import scala.annotation.tailrec
import scala.collection.immutable.ListMap

/** Parser for [[https://dl.acm.org/doi/10.1145/3385412.3385983 Aetherling]].
  */
object AetherlingParser {

  /** Parse a program from Aetherling's space-time language to an
    * [[mhir.ir.Expr]].
    *
    * ==Grammar==
    * The program must be generated by the following grammar:
    * {{{
    *   prog       ::= module+
    *   module     ::= ident param+ " =" assignment+ "\n\n"
    *   param      ::= " (" ident " :: " typ ")"
    *   typ        ::= "BitT"
    *                | "UInt8T"
    *                | "UInt32T"
    *                | "(ATupleT " typ " " typ ")"
    *                | "(SSeqT " nat " " typ ")"
    *                | "(TSeqT " nat " " nat " " typ ")"
    *   assignment ::= "\n    " ident " = " expr
    *   expr       ::= "(" expr ")"
    *                | ident
    *                | quot_ident
    *                | "AddN " typ " " expr
    *                | "Const_GenN " const " " nat " " typ
    *                | "ATupleN " typ " " typ " " expr " " expr
    *                | "FIFON " typ " " nat " " expr
    *                | "Map_tN " nat " " nat " " expr " " expr
    *                | "Map_sN " nat " " expr " " expr
    *                | ... (TODO)
    *   const      ::= "UInt8V " nat
    *                | "UInt32V " nat
    *                | ... (TODO)
    *   ident      ::= letter (letter | digit)*
    *   quot_ident ::= "\"" ident "\""
    *   nat        ::= digit+
    * }}}
    *
    * @param code
    *   an Atherling program.
    * @throws SyntaxError
    *   if the program is syntactically invalid.
    */
  def parse(code: String): Expr = {
    parseProgram(code, ListMap())
  }

  @tailrec
  private def parseProgram(
      code: String,
      modules: ListMap[Param, Function]
  ): Expr = {
    val (modName, modImpl, suffix) = parseModule(code, modules)
    if (suffix.isBlank) {
      Lets(modules.toSeq: _*)(modImpl)
    } else {
      parseProgram(suffix, modules + (modName -> modImpl))
    }
  }

  private def parseModule(
      code: String,
      modules: ListMap[Param, Function]
  ): (Param, Function, String) = {
    val (name, suffix0) = parseIdentifier(code)
    val (params, suffix1) = parseOneOrMoreParams(suffix0, Seq())
    val suffix2 = expect(suffix1, " =")
    val (assignments, suffix3) =
      parseOneOrMoreAssignments(suffix2, modules, ListMap())
    val suffix4 = expect(suffix3, "\n\n")
    val func = {
      val body = Lets(assignments.toSeq.init: _*)(assignments.last._2)
      val x0 = params.last
      val f0 = Function(x0, body)()
      params.init.foldRight(f0)({ case (x, body) => Function(x, body)() })
    }
    (name, func, suffix4)
  }

  private def parseIdentifier(code: String): (Param, String) = {
    if (code.isEmpty || !code.head.isLetter) {
      throw new SyntaxError(s"Expected an identifier but got $code")
    }
    val (name, suffix) = code.span(c => c.isLetterOrDigit)
    (Param(name, -1)(Missing), suffix)
  }

  private def parseQuotedIdentifier(code: String): (Param, String) = {
    val suffix0 = expect(code, "\"")
    val (x, suffix1) = parseIdentifier(suffix0)
    val suffix2 = expect(suffix1, "\"")
    (x, suffix2)
  }

  @tailrec
  private def parseOneOrMoreParams(
      code: String,
      params: Seq[Param]
  ): (Seq[Param], String) = {
    val (x, suffix) = parseParam(code)
    if (suffix.startsWith(" (")) {
      parseOneOrMoreParams(suffix, params :+ x)
    } else {
      (params :+ x, suffix)
    }
  }

  private def parseParam(code: String): (Param, String) = {
    val suffix0 = expect(code, " (")
    val (name, suffix1) = parseIdentifier(suffix0)
    val suffix2 = expect(suffix1, " :: ")
    val (typ, suffix3) = parseTyp(suffix2)
    val suffix4 = expect(suffix3, ")")
    (name.rebuild(typ).asInstanceOf[Param], suffix4)
  }

  @tailrec
  private def parseOneOrMoreAssignments(
      code: String,
      modules: ListMap[Param, Function],
      assignments: ListMap[Param, Expr]
  ): (ListMap[Param, Expr], String) = {
    val (x, v, suffix) = parseAssignment(code, modules)
    if (suffix.startsWith("\n    ")) {
      parseOneOrMoreAssignments(suffix, modules, assignments + (x -> v))
    } else {
      (assignments + (x -> v), suffix)
    }
  }

  private def parseAssignment(
      code: String,
      modules: ListMap[Param, Function]
  ): (Param, Expr, String) = {
    val suffix0 = expect(code, "\n    ")
    val (x, suffix1) = parseIdentifier(suffix0)
    val suffix2 = expect(suffix1, " = ")
    val (v, suffix3) = parseExpr(suffix2, modules)
    (x, v, suffix3)
  }

  private def parseTyp(code: String): (Type, String) = {
    if (code.startsWith("BitT")) {
      (TyBool, expect(code, "BitT"))
    } else if (code.startsWith("UInt8T")) {
      (U8, expect(code, "UInt8T"))
    } else if (code.startsWith("UInt32T")) {
      (U32, expect(code, "UInt32T"))
    } else if (code.startsWith("(ATupleT ")) {
      val suffix0 = expect(code, "(ATupleT ")
      val (t0, suffix1) = parseTyp(suffix0)
      val suffix2 = expect(suffix1, " ")
      val (t1, suffix3) = parseTyp(suffix2)
      val suffix4 = expect(suffix3, ")")
      (TyTuple(t0, t1), suffix4)
    } else if (code.startsWith("(SSeqT ")) {
      val suffix0 = expect(code, "(SSeqT ")
      val (n, suffix1) = parseNat(suffix0)
      val suffix2 = expect(suffix1, " ")
      val (t, suffix3) = parseTyp(suffix2)
      val suffix4 = expect(suffix3, ")")
      (TyVec(t, n), suffix4)
    } else if (code.startsWith("(TSeqT ")) {
      val suffix0 = expect(code, "(TSeqT ")
      val (n, suffix1) = parseNat(suffix0)
      val suffix2 = expect(suffix1, " ")
      val (_, suffix3) = parseNat(suffix2)
      val suffix4 = expect(suffix3, " ")
      val (t, suffix5) = parseTyp(suffix4)
      val suffix6 = expect(suffix5, ")")
      (TyStm(t, n), suffix6)
    } else {
      throw new SyntaxError(s"Expected a type but got $code")
    }
  }

  private def parseNat(code: String): (Int, String) = {
    val (nStr, suffix) = code.span(c => c.isDigit)
    if (nStr.isEmpty) {
      throw new SyntaxError(s"Expected a natural number but got $code")
    }
    val n = Integer.parseUnsignedInt(nStr)
    (n, suffix)
  }

  private def parseExpr(
      code: String,
      modules: ListMap[Param, Function]
  ): (Expr, String) = {
    if (code.startsWith("(")) {
      val suffix0 = expect(code, "(")
      val (e, suffix1) = parseExpr(suffix0, modules)
      val suffix2 = expect(suffix1, ")")
      (e, suffix2)
    } else if (code.startsWith("AddN ")) {
      val suffix0 = expect(code, "AddN ")
      // TODO: Add a node like `AssertType` which is removed by the type
      //       checker?
      val (_, suffix1) = parseTyp(suffix0)
      val suffix2 = expect(suffix1, " ")
      val (e, suffix3) = parseExpr(suffix2, modules)
      (e.__0 + e.__1, suffix3)
    } else if (code.startsWith("Const_GenN ")) {
      val suffix0 = expect(code, "Const_GenN ")
      val (c, suffix1) = parseConst(suffix0)
      val suffix2 = expect(suffix1, " ")
      val (_, suffix3) = parseNat(suffix2)
      val suffix4 = expect(suffix3, " ")
      // TODO: Assert type?
      val (_, suffix5) = parseTyp(suffix4)
      (c, suffix5)
    } else if (code.startsWith("ATupleN ")) {
      // TODO: Assert type?
      val suffix0 = expect(code, "ATupleN ")
      val (_, suffix1) = parseTyp(suffix0)
      val suffix2 = expect(suffix1, " ")
      val (_, suffix3) = parseTyp(suffix2)
      val suffix4 = expect(suffix3, " ")
      val (e0, suffix5) = parseExpr(suffix4, modules)
      val suffix6 = expect(suffix5, " ")
      val (e1, suffix7) = parseExpr(suffix6, modules)
      (Tuple(e0, e1)(), suffix7)
    } else if (code.startsWith("FIFON ")) {
      val suffix0 = expect(code, "FIFON ")
      // TODO: Assert type?
      val (_, suffix1) = parseTyp(suffix0)
      val suffix2 = expect(suffix1, " ")
      val (_, suffix3) = parseNat(suffix2)
      val suffix4 = expect(suffix3, " ")
      val (e, suffix5) = parseExpr(suffix4, modules)
      (Fifo(e), suffix5)
    } else if (code.startsWith("Map_tN ")) {
      val suffix0 = expect(code, "Map_tN ")
      val (_, suffix1) = parseNat(suffix0)
      val suffix2 = expect(suffix1, " ")
      val (_, suffix3) = parseNat(suffix2)
      val suffix4 = expect(suffix3, " ")
      val (f, suffix5) = parseExpr(suffix4, modules)
      val suffix6 = expect(suffix5, " ")
      val (s, suffix7) = parseExpr(suffix6, modules)
      // The function in StmMap must be a literal function
      val g: Function = f match {
        case x: Param if modules.contains(x) =>
          modules(x)
        case _ =>
          Function(Param("I", -1)(Missing), f)()
      }
      (StmMap(s, g)(), suffix7)
    } else if (code.startsWith("Map_sN ")) {
      val suffix0 = expect(code, "Map_sN ")
      // TODO: Assert type?
      val (_, suffix1) = parseNat(suffix0)
      val suffix2 = expect(suffix1, " ")
      val (f, suffix3) = parseExpr(suffix2, modules)
      val suffix4 = expect(suffix3, " ")
      val (v, suffix5) = parseExpr(suffix4, modules)
      (VecMap(v, f)(), suffix5)
    } else if (code.startsWith("\"")) {
      parseQuotedIdentifier(code)
    } else if (code.head.isLetter) {
      parseIdentifier(code)
    } else {
      throw new SyntaxError(s"Expected an expression but got $code")
    }
  }

  private def parseConst(code: String): (Expr, String) = {
    if (code.startsWith("UInt8V ")) {
      val suffix0 = expect(code, "UInt8V ")
      val (n, suffix1) = parseNat(suffix0)
      (C(n)(U8), suffix1)
    } else if (code.startsWith("UInt32V ")) {
      val suffix0 = expect(code, "UInt32V ")
      val (n, suffix1) = parseNat(suffix0)
      (C(n)(U32), suffix1)
    } else {
      throw new SyntaxError(s"Expected a constant but got $code")
    }
  }

  private def expect(code: String, prefix: String): String = {
    if (!code.startsWith(prefix)) {
      throw new SyntaxError(s"Expected '$prefix' but got $code")
    }
    code.substring(prefix.length)
  }
}
