#!/bin/sh

set -u

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

# If you want to allow non-ASCII filenames set this variable to true.
allownonascii=$(git config --type=bool hooks.allownonascii)

# Redirect output to stderr.
exec 1>&2

# Cross platform projects tend to avoid non-ASCII filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
if [ "$allownonascii" != "true" ] &&
	# Note that the use of brackets around a tr range is ok here, (it's
	# even required, for portability to Solaris 10's /usr/bin/tr), since
	# the square bracket bytes happen to fall in the designated range.
	test $(git diff --cached --name-only --diff-filter=A -z $against |
	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
then
	cat <<\EOF
Error: Attempt to add a non-ASCII file name.

This can cause problems if you want to work with people on other platforms.

To be portable it is advisable to rename the file.

If you know what you are doing you can disable this check using:

  git config hooks.allownonascii true
EOF
	exit 1
fi

set -e

cd "$(git rev-parse --show-toplevel)"
LOGS_DIR="$(pwd)/githooks/logs"
mkdir -p "$LOGS_DIR"

##### Scala-related tests ######################################################

if [ -n "${SKIP_SCALA:-}" ]; then
    SKIP_SCALAFMT='1'
    SKIP_SBT_TESTS='1'
    SKIP_E2E_TESTS='1'
fi

if [ -z "${SKIP_SCALAFMT:-}" ]; then
    echo "Running scalafmt (skip by defining SKIP_SCALA or SKIP_SCALAFMT)..."
    logs="$LOGS_DIR/scalafmt.log"
    scalafmt --check --exclude ./lib,./src/test/aetherling,./src/test/shir >"$logs" 2>&1 || {
        echo "Some files are mis-formatted. Please format them using scalafmt."
        echo "See $logs for details."
        exit 1
    }
    echo ""
fi

if [ -z "${SKIP_SBT_TESTS:-}" ]; then
    echo "Running unit tests with sbt (skip by defining SKIP_SCALA or SKIP_SBT_TESTS)..."
    logs="$LOGS_DIR/sbt_tests.log"
    sbt 'testQuick * -- -l mhir.testing.HardwareTest -l org.scalatest.tags.Slow' >"$logs" 2>&1 || {
        echo "Unit tests failed."
        echo "See $logs for details."
        exit 1
    }
    echo ""
fi

if [ -e .venv/bin/activate ]; then
    . .venv/bin/activate
fi

if [ -z "${SKIP_E2E_TESTS:-}" ]; then
    echo "Running end-to-end tests (skip by defining SKIP_SCALA or SKIP_E2E_TESTS)..."
    logs="$LOGS_DIR/e2e_tests.log"
    # I don't want to have to check out the Quartus license for each and every
    # commit, so just skip the vsim-related tests here
    ./src/e2e/python/run.py --skip-vsim >"$logs" 2>&1 || {
        echo "End-to-end tests failed."
        echo "See $logs for details."
        exit 1
    }
    echo ""
fi

##### Python-related tests #####################################################

if [ -n "${SKIP_PYTHON:-}" ]; then
    SKIP_PYTHON_SRC_TEST='1'
    SKIP_PYTHON_SRC_E2E='1'
    SKIP_PYTHON_DOCS='1'
fi

if [ -z "${SKIP_PYTHON_SRC_TEST:-}" ]; then
    # It seems we need to be in the right directory for pyright to accept the relative imports
    cd ./src/test/python
    echo "Checking Python code in $(pwd) (skip by defining SKIP_PYTHON or SKIP_PYTHON_SRC_TEST)..."
    logs="$LOGS_DIR/python_src_test.log"
    pyright . --project .pyrightconfig.json >"$logs" 2>&1 || {
        echo "pyright checks failed."
        echo "See $logs for details."
        exit 1
    }
    pylint . --rcfile ../../../.pylintrc >>"$logs" 2>&1 || {
        echo "pylint checks failed."
        echo "See $logs for details."
        exit 1
    }
    cd - >/dev/null
    echo ""
fi

if [ -z "${SKIP_PYTHON_SRC_E2E:-}" ]; then
    # It seems we need to be in the right directory for pyright to accept the relative imports
    cd ./src/e2e/python
    echo "Checking Python code in $(pwd) (skip by defining SKIP_PYTHON or SKIP_PYTHON_SRC_E2E)..."
    logs="$LOGS_DIR/python_src_e2e.log"
    pyright . --project .pyrightconfig.json >"$logs" 2>&1 || {
        echo "pyright checks failed."
        echo "See $logs for details."
        exit 1
    }
    pylint . --rcfile ../../../.pylintrc >>"$logs" 2>&1 || {
        echo "pylint checks failed."
        echo "See $logs for details"
        exit 1
    }
    cd - >/dev/null
    echo ""
fi

if [ -z "${SKIP_PYTHON_DOCS:-}" ]; then
    # It seems we need to be in the right directory for pyright to accept the relative imports
    cd ./docs/source
    echo "Checking Python code in $(pwd) (skip by defining SKIP_PYTHON or SKIP_PYTHON_DOCS)..."
    logs="$LOGS_DIR/python_docs.log"
    pyright . --project .pyrightconfig.json >"$logs" 2>&1 || {
        echo "pyright checks failed."
        echo "See $logs for details."
        exit 1
    }
    pylint . --rcfile ../../.pylintrc >>"$logs" 2>&1 || {
        echo "pylint checks failed."
        echo "See $logs for details."
        exit 1
    }
    cd - >/dev/null
    echo ""
fi

##### Documentation website checks #############################################

if [ -z "${SKIP_DOCS:-}" ]; then
    echo "Testing documentation website (skip by defining SKIP_DOCS)..."
    logs="$LOGS_DIR/docs.log"
    cd docs
    make html >"$logs" 2>&1 || {
        echo "Command 'make html' failed"
        echo "See $logs for details."
        exit 1
    }
    make linkcheck >>"$logs" 2>&1 || {
        echo "Command 'make linkcheck' failed"
        echo "See $logs for details."
        exit 1
    }
    cd - > /dev/null
    echo ""
fi

# If there are whitespace errors, print the offending file names and fail.
exec git diff-index --check --cached $against --
