#!/bin/sh

set -u

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

# If you want to allow non-ASCII filenames set this variable to true.
allownonascii=$(git config --type=bool hooks.allownonascii)

# Redirect output to stderr.
exec 1>&2

# Cross platform projects tend to avoid non-ASCII filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
if [ "$allownonascii" != "true" ] &&
	# Note that the use of brackets around a tr range is ok here, (it's
	# even required, for portability to Solaris 10's /usr/bin/tr), since
	# the square bracket bytes happen to fall in the designated range.
	test $(git diff --cached --name-only --diff-filter=A -z $against |
	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
then
	cat <<\EOF
Error: Attempt to add a non-ASCII file name.

This can cause problems if you want to work with people on other platforms.

To be portable it is advisable to rename the file.

If you know what you are doing you can disable this check using:

  git config hooks.allownonascii true
EOF
	exit 1
fi

set -e
cd "$(git rev-parse --show-toplevel)"

if [ -z "${SKIP_SCALAFMT:-}" ]; then
    echo "Running scalafmt (skip by defining SKIP_SCALAFMT)..."
    scalafmt --check --quiet --exclude ./lib,./src/test/aetherling,./src/test/shir || {
        echo "Some files are mis-formatted. Please format them using scalafmt."
        exit 1
    }
    echo ""
fi

if [ -z "${SKIP_SBT_TESTS:-}" ]; then
    echo "Running unit tests with sbt (skip by defining SKIP_SBT_TESTS)..."
    sbt 'testQuick * -- -l mhir.testing.HardwareTest -l org.scalatest.tags.Slow' || {
        echo "Unit tests failed."
        exit 1
    }
    echo ""
fi

if [ -e .venv/bin/activate ]; then
    . .venv/bin/activate
fi

if [ -z "${SKIP_E2E_TESTS:-}" ]; then
    echo "Running end-to-end tests (skip by defining SKIP_E2E_TESTS)..."
    # I don't want to have to check out the Quartus license for each and every
    # commit, so just skip the vsim-related tests here
    ./src/e2e/python/run.py --skip-vsim || {
        echo "End-to-end tests failed."
        exit 1
    }
    echo ""
fi

if [ -z "${SKIP_SRC_TEST_PYTHON:-}" ]; then
    # It seems we need to be in the right directory for pyright to accept the relative imports
    cd ./src/test/python
    echo "Checking Python code in $(pwd) (skip by defining SKIP_SRC_TEST_PYTHON)..."
    pyright . --project .pyrightconfig.json
    pylint  . --rcfile  ../../../.pylintrc
    cd - >/dev/null
    echo ""
fi

if [ -z "${SKIP_SRC_E2E_PYTHON:-}" ]; then
    # It seems we need to be in the right directory for pyright to accept the relative imports
    cd ./src/e2e/python
    echo "Checking Python code in $(pwd) (skip by defining SKIP_SRC_E2E_PYTHON)..."
    pyright . --project .pyrightconfig.json
    pylint  . --rcfile  ../../../.pylintrc
    cd - >/dev/null
    echo ""
fi

if [ -z "${SKIP_DOCS_PYTHON:-}" ]; then
    # It seems we need to be in the right directory for pyright to accept the relative imports
    cd ./docs/source
    echo "Checking Python code in $(pwd) (skip by defining SKIP_DOCS_PYTHON)..."
    pyright . --project .pyrightconfig.json
    pylint  . --rcfile  ../../.pylintrc
    cd - >/dev/null
    echo ""
fi

if [ -z "${SKIP_DOCS:-}" ]; then
    echo "Testing documentation website..."
    cd docs
    make html >/dev/null || {
        echo "Command 'make html' failed"
        exit 1
    }
    make linkcheck || {
        echo "Command 'make linkcheck' failed"
        exit 1
    }
    cd - > /dev/null
fi

# If there are whitespace errors, print the offending file names and fail.
exec git diff-index --check --cached $against --
