package mhir.main.aetherling

import mhir.ir._
import org.scalatest.funsuite.AnyFunSuite
import mhir.optimize.{NameSimplifier => NS}
import org.scalatest.tagobjects.Slow

/** Tests to ensure the simplified minimalist IR expressions for the Aetherling
  * benchmarks don't change unexpectedly.
  *
  * If the expression for a given benchmark changes, the measurements (e.g.,
  * resource usage) should be re-run, since they may have changed.
  */
class AetherlingBenchmarkChangeTests extends AnyFunSuite {
  private val AetherlingBenchmarksDir =
    os.pwd / "src" / "test" / "resources" / "aetherling_benchmarks" / "original"
  private val SimplifiedAetherlingBenchmarksDir =
    os.pwd / "src" / "test" / "resources" / "aetherling_benchmarks" / "simplified"
  private val VhdlDir = os.pwd / "src" / "test" / "vhdl"

  /** Whether to save the parsed programs to
    * [[SimplifiedAetherlingBenchmarksDir]].
    *
    * If false, then the programs in [[SimplifiedAetherlingBenchmarksDir]] will
    * be used as the expected outputs and nothing will be written.
    *
    * If true, then the compiler outputs will be saved to
    * [[SimplifiedAetherlingBenchmarksDir]]. This is useful in case you want to
    * change the expected outputs, just don't forget to review the outputs and
    * change this field back to `false`.
    */
  private val SaveChanges: Boolean = false

  private val SlowBenchmarks: Set[String] = Set("conv1d", "smallconv2d")

  test("SaveChanges") {
    assert(!SaveChanges)
  }

  for (f <- os.list(AetherlingBenchmarksDir)) {
    val benchName = f.baseName
    val isSlow =
      SlowBenchmarks.exists(name => benchName.startsWith(s"${name}_"))
    val tags = if (isSlow) Seq(Slow) else Seq()

    test(benchName, tags: _*) {
      if (benchName == "smallconvb2b_16") ??? // Waaay too slow
      mhir.ir.reset()
      val inFile = AetherlingBenchmarksDir / s"$benchName.txt"
      val outDir = VhdlDir / "aetherling" / s"${benchName}_test"
      val args = Args(inFile = inFile, outDir = outDir, emitHdl = false)
      val f = Compiler.compile(args)
      val actual = ExprPrinter.display(NS.simplify(f))
      val expectedPath = SimplifiedAetherlingBenchmarksDir / s"$benchName.txt"
      if (SaveChanges) {
        os.write.over(expectedPath, actual)
      } else {
        val expected = os.read(expectedPath)
        if (actual != expected) {
          fail(
            "the final program generated by the compiler seems to have changed,"
              + " which may invalidate previous measurements (e.g., resource usage, fmax)"
          )
        }
      }
      assume(!SaveChanges)
    }
  }
}
