package mhir.main.aetherling

import mhir.gen.verilog.{
  VerilogProjectInitializer,
  VerilogTestRunner,
  VerilogTestbenchGenerator
}
import mhir.gen.vhdl.{VhdlTestRunner, VhdlTestbenchGenerator}
import mhir.gen.{TestInput, TestOutput, TestPassed, Undefined}
import mhir.ir._
import mhir.testing.HardwareTest
import org.scalatest.funsuite.AnyFunSuite

/** Tests that the VHDL designs produced by [[mhir.main.aetherling.Compiler]]
  * behave the same as the Verilog designs generated by
  * [[https://dl.acm.org/doi/10.1145/3385412.3385983 Aetherling]].
  */
@HardwareTest
class AetherlingBenchmarkTests extends AnyFunSuite {
  private val AetherlingBenchmarksDir =
    os.pwd / "src" / "test" / "resources" / "aetherling_benchmarks" / "original"
  private val VerilogBenchmarksDir =
    os.pwd / "src" / "test" / "resources" / "aetherling_benchmarks" / "verilog"
  private val VhdlDir = os.pwd / "src" / "test" / "vhdl"
  private val VerilogDir = os.pwd / "src" / "test" / "verilog"

  private val AllBenchmarks = os.list(AetherlingBenchmarksDir).map(_.baseName)
  private val BenchmarksToRun = AllBenchmarks

  test("AllBenchmarks") {
    assert(BenchmarksToRun == AllBenchmarks)
  }

  for (benchName <- BenchmarksToRun) {
    test(s"$benchName:vhdl:simplified") {
      val (inputs, outputs) =
        AetherlingBenchmarkTests.ioByBenchmark(s"$benchName:vhdl")
      val inFile = AetherlingBenchmarksDir / s"$benchName.txt"
      val outDir = VhdlDir / "aetherling" / s"${benchName}_test"
      if (os.exists(outDir)) os.remove.all(outDir)
      val args = Args(inFile = inFile, outDir = outDir)
      Compiler.compile(args)
      VhdlTestbenchGenerator.makeTestbench(
        inputs = inputs,
        out = outputs,
        dir = outDir,
        testNotReady = false
      )
      assert(VhdlTestRunner.testExistingProject(outDir) == TestPassed)
    }

    test(s"$benchName:vhdl:unsimplified") {
      val (inputs, outputs) =
        AetherlingBenchmarkTests.ioByBenchmark(s"$benchName:vhdl")
      val inFile = AetherlingBenchmarksDir / s"$benchName.txt"
      val outDir = VhdlDir / "aetherling" / s"${benchName}_test_unsimplified"
      if (os.exists(outDir)) os.remove.all(outDir)
      val args = Args(inFile = inFile, outDir = outDir, optimize = false)
      Compiler.compile(args)
      VhdlTestbenchGenerator.makeTestbench(
        inputs = inputs,
        out = outputs,
        dir = outDir,
        testNotReady = false
      )
      assert(VhdlTestRunner.testExistingProject(outDir) == TestPassed)
    }

    test(s"$benchName:verilog") {
      assume(
        benchName != "conv1d_1_3",
        "I can't quite get this one working."
          + " If I try running it with a kernel of [0, 1, 0] and inputs 0, 1, 2, 3, ...,"
          + " it seems I need to hold each input for three cycles with valid always up."
          + " But if I try using that same strategy for the actual test case,"
          + " I don't get the right outputs."
      )
      val (inputs, outputs) =
        AetherlingBenchmarkTests.ioByBenchmark(s"$benchName:verilog")
      val projectDir = VerilogDir / s"aetherling" / s"${benchName}_test"
      VerilogProjectInitializer.initProj(
        projectDir,
        VerilogBenchmarksDir / s"$benchName.v",
        overwrite = true
      )
      VerilogTestbenchGenerator.makeTestbench(inputs, outputs, projectDir)
      assert(VerilogTestRunner.testExistingProject(projectDir) == TestPassed)
    }
  }
}

object AetherlingBenchmarkTests {

  private val mapIO: Map[String, (Seq[TestInput], TestOutput)] = {
    val flatInputs = (0 until 200).map(i => C(i)(U8))
    val flatOutputs = (0 until 200).map(i => C(i + 5)(U8))
    Seq(1, 2, 4, 5, 8, 10, 20, 40, 200)
      .map(par => {
        val (inputs, outputs) = par match {
          case 1 =>
            (
              TestInput(flatInputs.map(e => Some(e))),
              TestOutput(flatOutputs)
            )
          case _ =>
            (
              TestInput(
                flatInputs
                  .grouped(par)
                  .map(xs => Some(VecLiteral(xs: _*)()))
                  .toSeq
              ),
              TestOutput(
                flatOutputs
                  .grouped(par)
                  .map(xs => VecLiteral(xs: _*)())
                  .toSeq
              )
            )
        }
        s"map_$par" -> (Seq(inputs), outputs)
      })
      .flatMap({ case (name, io) =>
        Seq(s"$name:vhdl" -> io, s"$name:verilog" -> io)
      })
      .toMap
  }

  private val sumIO: Map[String, (Seq[TestInput], TestOutput)] = {
    val flatInputs = (0 until 840).map(i => C(i)(U32))
    val sum = C((0 until 840).sum)(U32)
    Seq(1, 2, 3, 4, 5, 6, 7, 8)
      .map(par => {
        val inputs = par match {
          case 1 =>
            TestInput(flatInputs.map(e => Some(e)))
          case _ =>
            TestInput(
              flatInputs
                .grouped(par)
                .map(xs => Some(VecLiteral(xs: _*)()))
                .toSeq
            )
        }
        s"sum_1_${840 / par}" -> (Seq(inputs), TestOutput(Seq(sum)))
      })
      .flatMap({ case (name, io) =>
        Seq(s"$name:vhdl" -> io, s"$name:verilog" -> io)
      })
      .toMap
  }

  private val dotIO: Map[String, (Seq[TestInput], TestOutput)] = {
    val flatInputs1 = (0 until 840).map(_ % 16)
    val flatInputs2 = (839 to 0 by -1).map(_ % 16)
    val result =
      flatInputs1.zip(flatInputs2).map({ case (x, y) => x * y }).sum
    Seq(1, 2, 3, 4, 5, 6, 7, 8)
      .map(par => {
        val (inputs1, inputs2) = par match {
          case 1 =>
            (
              TestInput(flatInputs1.map(e => Some(C(e)(U16)))),
              TestInput(flatInputs2.map(e => Some(C(e)(U16))))
            )
          case _ =>
            (
              TestInput(
                flatInputs1
                  .grouped(par)
                  .map(xs => Some(VecLiteral(xs.map(C(_)(U16)): _*)()))
                  .toSeq
              ),
              TestInput(
                flatInputs2
                  .grouped(par)
                  .map(xs => Some(VecLiteral(xs.map(C(_)(U16)): _*)()))
                  .toSeq
              )
            )
        }
        s"dot_1_${840 / par}" -> (
          Seq(inputs1, inputs2),
          TestOutput(Seq(C(result)(U16)))
        )
      })
      .flatMap({ case (name, io) =>
        Seq(s"$name:vhdl" -> io, s"$name:verilog" -> io)
      })
      .toMap
  }

  private val conv1dIO: Map[String, (Seq[TestInput], TestOutput)] = {
    // Square wave with 50% duty cycle and period 8
    val flatInputs = (0 until 16).map(t => if (t % 8 < 4) -42 else 42)
    val flatOutputs =
      (Seq(Undefined(I8), Undefined(I8))
        ++ flatInputs.sliding(3).map(v => C(v(2) - v(0))(I8)).toSeq)
    val normalCases = Seq(1, 2, 4, 8, 16)
      .map({ par =>
        val (inputs, outputs) = par match {
          case 1 =>
            (
              TestInput(
                flatInputs.map(C(_)(I8)).map(VecLiteral(_)()).map(Some(_))
              ),
              TestOutput(flatOutputs.map(VecLiteral(_)()))
            )
          case n =>
            assert(n > 1)
            // n valid per cycle
            (
              TestInput(
                flatInputs
                  .grouped(n)
                  .map(xs => VecLiteral(xs.map(C(_)(I8)): _*)())
                  .map(Some(_))
                  .toSeq
              ),
              TestOutput(
                flatOutputs
                  .grouped(n)
                  .map(xs => VecLiteral(xs.map(VecLiteral(_)()): _*)())
                  .toSeq
              )
            )
        }
        s"conv1d_$par" -> (Seq(inputs), outputs)
      })
      .flatMap({ case (name, io) =>
        Seq(s"$name:vhdl" -> io, s"$name:verilog" -> io)
      })
      .toMap
    val vhdlUnderutilizedCase =
      "conv1d_1_3:vhdl" -> (
        Seq(
          TestInput(
            flatInputs.flatMap(x => Seq(Some(C(x)(I8)), None, None))
          )
        ),
        TestOutput(flatOutputs)
      )
    val verilogUnderutilizedCase =
      "conv1d_1_3:verilog" -> (
        Seq(
          TestInput(
            flatInputs.flatMap(x =>
              Seq(Some(C(x)(I8)), Some(C(x)(I8)), Some(C(x)(I8)))
            )
          )
        ),
        TestOutput(
          flatOutputs.flatMap(x => Seq(x, Undefined(I8), Undefined(I8)))
        )
      )
    (normalCases + vhdlUnderutilizedCase) + verilogUnderutilizedCase
  }

  private val smallConv2dIO: Map[String, (Seq[TestInput], TestOutput)] = {
    // Checkerboard pattern (2x2 squares)
    val basicInputs: Seq[Seq[Int]] =
      (0 until 4).map(i =>
        (0 until 4).map(j => {
          val even = ((i % 4) < 2) == ((j % 4) < 2)
          if (even) 15 else 0
        })
      )
    val basicInputExprs = basicInputs.flatten.map(C(_)(U8))
    val kernel = Seq(Seq(1, 2, 1), Seq(2, 4, 2), Seq(1, 2, 1)).flatten
    val kernelDenom = 16
    val basicOutputs: Seq[Expr] =
      (-1 to 2).flatMap(i =>
        (-1 to 2).map(j =>
          if (i < 1 || j < 1) {
            Undefined(U8)
          } else {
            val inputs = (-1 to 1).flatMap(deltaI =>
              (-1 to 1).map(deltaJ => basicInputs(i + deltaI)(j + deltaJ))
            )
            val dot = inputs.zip(kernel).map({ case (x, y) => x * y }).sum
            C(dot / kernelDenom)(U8)
          }
        )
      )
    val normalCases = Seq(1, 2, 4, 8, 16)
      .map({ par =>
        val (inputs, outputs) = par match {
          case 1 =>
            (
              TestInput(basicInputExprs.map(VecLiteral(_)()).map(Some(_))),
              TestOutput(basicOutputs.map(VecLiteral(_)()))
            )
          case n =>
            assert(n > 1)
            // n valid per cycle
            (
              TestInput(
                basicInputExprs
                  .grouped(n)
                  .map(VecLiteral(_: _*)())
                  .map(Some(_))
                  .toSeq
              ),
              TestOutput(
                basicOutputs
                  .grouped(n)
                  .map(VecLiteral(_: _*)())
                  .toSeq
              )
            )
        }
        s"smallconv2d_$par" -> (Seq(inputs), outputs)
      })
      .flatMap({ case (name, io) =>
        Seq(s"$name:vhdl" -> io, s"$name:verilog" -> io)
      })
      .toMap
    val verilogUnderutilizedCases = Seq(3, 9)
      .map({ denom =>
        val inputs = TestInput(
          basicInputExprs.flatMap(x => (0 until denom).map(_ => Some(x)))
        )
        val outputs = TestOutput(
          basicOutputs.flatMap(x =>
            x +: (0 until (denom - 1)).map(_ => Undefined(U8))
          )
        )
        s"smallconv2d_1_$denom:verilog" -> (Seq(inputs), outputs)
      })
      .toMap
    val vhdlUnderutilizedCases = Seq(3, 9)
      .map({ denom =>
        val inputs = TestInput(basicInputExprs.map(Some(_)))
        val outputs = TestOutput(basicOutputs)
        s"smallconv2d_1_$denom:vhdl" -> (Seq(inputs), outputs)
      })
    normalCases ++ verilogUnderutilizedCases ++ vhdlUnderutilizedCases
  }

  /** Maps benchmark names (e.g., "dot_1_105:vhdl") to inputs and expected
    * outputs.
    *
    * @note
    *   this must be manually updated whenever a new benchmark is added.
    */
  val ioByBenchmark: Map[String, (Seq[TestInput], TestOutput)] = (
    mapIO
      ++ sumIO
      ++ dotIO
      ++ conv1dIO
      ++ smallConv2dIO
  )
}
