package mhir.main.aetherling

import com.typesafe.scalalogging.Logger
import mhir.gen.verilog.{
  VerilogProjectInitializer,
  VerilogTestRunner,
  VerilogTestbenchGenerator
}
import mhir.gen.vhdl.{VhdlTestRunner, VhdlTestbenchGenerator}
import mhir.gen.{TestInput, TestOutput, TestPassed, Undefined}
import mhir.ir._
import mhir.testing.HardwareTest
import org.scalatest.funsuite.AnyFunSuite
import mhir.logging.time

/** Tests that the VHDL designs produced by [[mhir.main.aetherling.Compiler]]
  * behave the same as the Verilog designs generated by
  * [[https://dl.acm.org/doi/10.1145/3385412.3385983 Aetherling]].
  */
@HardwareTest
class AetherlingBenchmarkTests extends AnyFunSuite {
  private val AetherlingBenchmarksDir =
    os.pwd / "src" / "test" / "resources" / "aetherling_benchmarks" / "original"
  private val VerilogBenchmarksDir =
    os.pwd / "src" / "test" / "resources" / "aetherling_benchmarks" / "verilog"
  private val VhdlDir = os.pwd / "src" / "test" / "vhdl"
  private val VerilogDir = os.pwd / "src" / "test" / "verilog"

  private val AllBenchmarks: Seq[String] =
    os.list(AetherlingBenchmarksDir).map(_.baseName)
  private val BenchmarksToRun: Seq[String] =
    AllBenchmarks.filter(_.startsWith("smallsharpen"))

  private implicit val logger: Logger = Logger(getClass.getName)

  test("AllBenchmarks") {
    assert(BenchmarksToRun == AllBenchmarks)
  }

  for (benchName <- BenchmarksToRun) {
    test(s"$benchName:vhdl:simplified") {
      val (inputs, outputs) =
        AetherlingBenchmarkTests.ioByBenchmark(s"$benchName:vhdl")
      val inFile = AetherlingBenchmarksDir / s"$benchName.txt"
      val outDir = VhdlDir / "aetherling" / s"${benchName}_test"
      if (os.exists(outDir)) os.remove.all(outDir)
      val args = Args(inFile = inFile, outDir = outDir)
      Compiler.compile(args)
      time("generating VHDL testbench") {
        VhdlTestbenchGenerator.makeTestbench(
          inputs = inputs,
          out = outputs,
          dir = outDir,
          testNotReady = false
        )
      }
      time("running VHDL simulation") {
        assert(VhdlTestRunner.testExistingProject(outDir) == TestPassed)
      }
    }

    ignore(s"$benchName:vhdl:unsimplified") {
      val (inputs, outputs) =
        AetherlingBenchmarkTests.ioByBenchmark(s"$benchName:vhdl")
      val inFile = AetherlingBenchmarksDir / s"$benchName.txt"
      val outDir = VhdlDir / "aetherling" / s"${benchName}_test_unsimplified"
      if (os.exists(outDir)) os.remove.all(outDir)
      val args = Args(inFile = inFile, outDir = outDir, optimize = false)
      Compiler.compile(args)
      time("generating VHDL testbench") {
        VhdlTestbenchGenerator.makeTestbench(
          inputs = inputs,
          out = outputs,
          dir = outDir,
          testNotReady = false
        )
      }
      time("running VHDL simulation") {
        assert(VhdlTestRunner.testExistingProject(outDir) == TestPassed)
      }
    }

    test(s"$benchName:verilog") {
      assume(
        !benchName.contains("1_3") && !benchName.contains("1_9"),
        "I haven't managed to figure out how the Verilog designs with"
          + " throughput < 1 work."
      )
      assume(
        !benchName.startsWith("smallsharpen"),
        "None of the sharpening benchmarks work as expected in Verilog."
          + " In the timing diagram, it appears the image and blurred image"
          + " are arriving at the final stage (for sharpening one pixel)"
          + " at different times."
      )
      val (inputs, outputs) =
        AetherlingBenchmarkTests.ioByBenchmark(s"$benchName:verilog")
      val projectDir = VerilogDir / s"aetherling" / s"${benchName}_test"
      VerilogProjectInitializer.initProj(
        projectDir,
        VerilogBenchmarksDir / s"$benchName.v",
        overwrite = true
      )
      time("generating Verilog testbench") {
        VerilogTestbenchGenerator.makeTestbench(inputs, outputs, projectDir)
      }
      time("running Verilog simulation") {
        assert(VerilogTestRunner.testExistingProject(projectDir) == TestPassed)
      }
    }
  }
}

object AetherlingBenchmarkTests {

  /** Finds the width and height of a rectangular array.
    *
    * @param arr
    *   the array.
    * @return
    *   (width, height)
    */
  private def dim[T](arr: Seq[Seq[T]]): (Int, Int) = {
    val height = arr.length
    val width = {
      val widths = arr.map(_.length).toSet
      require(widths.size == 1)
      widths.head
    }
    (width, height)
  }

  /** Performs a 2D convolution
    *
    * @param inputs
    *   the input array. `None` values are considered undefined.
    * @param kernel
    *   the kernel.
    * @param kernelDenom
    *   a number by which to divide each element after the convolution.
    * @return
    *   the result of the convolution and division. `None` represents undefined
    *   values.
    */
  private def conv2d(
      inputs: Seq[Seq[Option[Int]]],
      kernel: Seq[Seq[Int]],
      kernelDenom: Int
  ): Seq[Seq[Option[Int]]] = {
    val (inputWidth, inputHeight) = dim(inputs)
    val (kernelWidth, kernelHeight) = dim(kernel)
    val outputs =
      ((1 - kernelHeight) to (inputHeight - kernelHeight)).map({ i =>
        ((1 - kernelWidth) to (inputWidth - kernelWidth)).map({ j =>
          // (i, j) is the current position of the top-left element of the
          // kernel within the input
          if (i < 0 || j < 0) {
            None
          } else {
            val relevantInputs =
              (0 until kernelHeight).flatMap(deltaI =>
                (0 until kernelWidth).map(deltaJ =>
                  inputs(i + deltaI)(j + deltaJ)
                )
              )
            if (relevantInputs.forall(_.nonEmpty)) {
              val dot = relevantInputs
                .map(_.get)
                .zip(kernel.flatten)
                .map({ case (x, y) => x * y })
                .sum
              Some(dot / kernelDenom)
            } else {
              None
            }
          }
        })
      })
    assert(dim(outputs) == dim(inputs))
    outputs
  }

  private val mapIO: Map[String, (Seq[TestInput], TestOutput)] = {
    val flatInputs = (0 until 200).map(i => C(i)(U8))
    val flatOutputs = (0 until 200).map(i => C(i + 5)(U8))
    Seq(1, 2, 4, 5, 8, 10, 20, 40, 200)
      .map(par => {
        val (inputs, outputs) = par match {
          case 1 =>
            (
              TestInput(flatInputs.map(e => Some(e))),
              TestOutput(flatOutputs)
            )
          case _ =>
            (
              TestInput(
                flatInputs
                  .grouped(par)
                  .map(xs => Some(VecLiteral(xs: _*)()))
                  .toSeq
              ),
              TestOutput(
                flatOutputs
                  .grouped(par)
                  .map(xs => VecLiteral(xs: _*)())
                  .toSeq
              )
            )
        }
        s"map_$par" -> (Seq(inputs), outputs)
      })
      .flatMap({ case (name, io) =>
        Seq(s"$name:vhdl" -> io, s"$name:verilog" -> io)
      })
      .toMap
  }

  private val sumIO: Map[String, (Seq[TestInput], TestOutput)] = {
    val flatInputs = (0 until 840).map(i => C(i)(U32))
    val sum = C((0 until 840).sum)(U32)
    Seq(1, 2, 3, 4, 5, 6, 7, 8)
      .map(par => {
        val inputs = par match {
          case 1 =>
            TestInput(flatInputs.map(e => Some(e)))
          case _ =>
            TestInput(
              flatInputs
                .grouped(par)
                .map(xs => Some(VecLiteral(xs: _*)()))
                .toSeq
            )
        }
        s"sum_1_${840 / par}" -> (Seq(inputs), TestOutput(Seq(sum)))
      })
      .flatMap({ case (name, io) =>
        Seq(s"$name:vhdl" -> io, s"$name:verilog" -> io)
      })
      .toMap
  }

  private val dotIO: Map[String, (Seq[TestInput], TestOutput)] = {
    val flatInputs1 = (0 until 840).map(_ % 16)
    val flatInputs2 = (839 to 0 by -1).map(_ % 16)
    val result =
      flatInputs1.zip(flatInputs2).map({ case (x, y) => x * y }).sum
    Seq(1, 2, 3, 4, 5, 6, 7, 8)
      .map(par => {
        val (inputs1, inputs2) = par match {
          case 1 =>
            (
              TestInput(flatInputs1.map(e => Some(C(e)(U16)))),
              TestInput(flatInputs2.map(e => Some(C(e)(U16))))
            )
          case _ =>
            (
              TestInput(
                flatInputs1
                  .grouped(par)
                  .map(xs => Some(VecLiteral(xs.map(C(_)(U16)): _*)()))
                  .toSeq
              ),
              TestInput(
                flatInputs2
                  .grouped(par)
                  .map(xs => Some(VecLiteral(xs.map(C(_)(U16)): _*)()))
                  .toSeq
              )
            )
        }
        s"dot_1_${840 / par}" -> (
          Seq(inputs1, inputs2),
          TestOutput(Seq(C(result)(U16)))
        )
      })
      .flatMap({ case (name, io) =>
        Seq(s"$name:vhdl" -> io, s"$name:verilog" -> io)
      })
      .toMap
  }

  private val conv1dIO: Map[String, (Seq[TestInput], TestOutput)] = {
    // Square wave with 50% duty cycle and period 8
    val flatInputs = (0 until 16).map(t => if (t % 8 < 4) -42 else 42)
    val flatOutputs =
      (Seq(Undefined(I8), Undefined(I8))
        ++ flatInputs.sliding(3).map(v => C(v(2) - v(0))(I8)).toSeq)
    val normalCases = Seq(1, 2, 4, 8, 16)
      .map({ par =>
        val (inputs, outputs) = par match {
          case 1 =>
            (
              TestInput(
                flatInputs.map(C(_)(I8)).map(VecLiteral(_)()).map(Some(_))
              ),
              TestOutput(flatOutputs.map(VecLiteral(_)()))
            )
          case n =>
            assert(n > 1)
            // n valid per cycle
            (
              TestInput(
                flatInputs
                  .grouped(n)
                  .map(xs => VecLiteral(xs.map(C(_)(I8)): _*)())
                  .map(Some(_))
                  .toSeq
              ),
              TestOutput(
                flatOutputs
                  .grouped(n)
                  .map(xs => VecLiteral(xs.map(VecLiteral(_)()): _*)())
                  .toSeq
              )
            )
        }
        s"conv1d_$par" -> (Seq(inputs), outputs)
      })
      .flatMap({ case (name, io) =>
        Seq(s"$name:vhdl" -> io, s"$name:verilog" -> io)
      })
      .toMap
    val vhdlUnderutilizedCase =
      "conv1d_1_3:vhdl" -> (
        Seq(
          TestInput(
            flatInputs.flatMap(x => Seq(Some(C(x)(I8)), None, None))
          )
        ),
        TestOutput(flatOutputs)
      )
    val verilogUnderutilizedCase =
      "conv1d_1_3:verilog" -> (
        Seq(
          TestInput(
            flatInputs.flatMap(x =>
              Seq(Some(C(x)(I8)), Some(C(x)(I8)), Some(C(x)(I8)))
            )
          )
        ),
        TestOutput(
          flatOutputs.flatMap(x => Seq(x, Undefined(I8), Undefined(I8)))
        )
      )
    (normalCases + vhdlUnderutilizedCase) + verilogUnderutilizedCase
  }

  private val smallConv2dIO: Map[String, (Seq[TestInput], TestOutput)] = {
    // Checkerboard pattern (2x2 squares)
    val basicInputs: Seq[Seq[Int]] =
      (0 until 4).map(i =>
        (0 until 4).map(j => {
          val even = ((i % 4) < 2) == ((j % 4) < 2)
          if (even) 15 else 0
        })
      )
    val basicInputExprs = basicInputs.flatten.map(C(_)(U8))
    val basicOutputs: Seq[Expr] =
      conv2d(
        basicInputs.map(_.map(Some(_))),
        kernel = Seq(Seq(1, 2, 1), Seq(2, 4, 2), Seq(1, 2, 1)),
        kernelDenom = 16
      ).flatten.map({
        case Some(x) => C(x)(U8)
        case None    => Undefined(U8)
      })
    val normalCases = Seq(1, 2, 4, 8, 16)
      .map({ par =>
        val (inputs, outputs) = par match {
          case 1 =>
            (
              TestInput(basicInputExprs.map(VecLiteral(_)()).map(Some(_))),
              TestOutput(basicOutputs.map(VecLiteral(_)()))
            )
          case n =>
            assert(n > 1)
            // n valid per cycle
            (
              TestInput(
                basicInputExprs
                  .grouped(n)
                  .map(VecLiteral(_: _*)())
                  .map(Some(_))
                  .toSeq
              ),
              TestOutput(
                basicOutputs
                  .grouped(n)
                  .map(VecLiteral(_: _*)())
                  .toSeq
              )
            )
        }
        s"smallconv2d_$par" -> (Seq(inputs), outputs)
      })
      .flatMap({ case (name, io) =>
        Seq(s"$name:vhdl" -> io, s"$name:verilog" -> io)
      })
      .toMap
    val verilogUnderutilizedCases = Seq(3, 9)
      .map({ denom =>
        val inputs = TestInput(
          basicInputExprs.flatMap(x => (0 until denom).map(_ => Some(x)))
        )
        val outputs = TestOutput(
          basicOutputs.flatMap(x =>
            x +: (0 until (denom - 1)).map(_ => Undefined(U8))
          )
        )
        s"smallconv2d_1_$denom:verilog" -> (Seq(inputs), outputs)
      })
      .toMap
    val vhdlUnderutilizedCases = Seq(3, 9)
      .map({ denom =>
        val inputs = TestInput(basicInputExprs.map(Some(_)))
        val outputs = TestOutput(basicOutputs)
        s"smallconv2d_1_$denom:vhdl" -> (Seq(inputs), outputs)
      })
    normalCases ++ verilogUnderutilizedCases ++ vhdlUnderutilizedCases
  }

  private val smallConvB2bIO: Map[String, (Seq[TestInput], TestOutput)] = {
    // Checkerboard pattern (2x2 squares)
    val basicInputs: Seq[Seq[Int]] =
      (0 until 4).map(i =>
        (0 until 4).map(j => {
          val even = ((i % 4) < 2) == ((j % 4) < 2)
          if (even) 15 else 0
        })
      )
    val basicInputExprs = basicInputs.flatten.map(C(_)(U8))
    val basicOutputs = {
      val step1 = conv2d(
        inputs = basicInputs.map(_.map(Some(_))),
        kernel = Seq(Seq(1, 2, 1), Seq(2, 4, 2), Seq(1, 2, 1)),
        kernelDenom = 16
      )
      val step2 = conv2d(
        inputs = step1,
        kernel = Seq(Seq(1, 4), Seq(2, 1)),
        kernelDenom = 8
      )
      step2.flatten.map({
        case Some(x) => C(x)(U8)
        case None    => Undefined(U8)
      })
    }
    val normalCases = Seq(1, 2, 4, 8, 16)
      .map({ par =>
        val (inputs, outputs) = par match {
          case 1 =>
            (
              TestInput(basicInputExprs.map(VecLiteral(_)()).map(Some(_))),
              TestOutput(basicOutputs.map(VecLiteral(_)()))
            )
          case n =>
            assert(n > 1)
            // n valid per cycle
            (
              TestInput(
                basicInputExprs
                  .grouped(n)
                  .map(VecLiteral(_: _*)())
                  .map(Some(_))
                  .toSeq
              ),
              TestOutput(
                basicOutputs
                  .grouped(n)
                  .map(VecLiteral(_: _*)())
                  .toSeq
              )
            )
        }
        s"smallconvb2b_$par" -> (Seq(inputs), outputs)
      })
      .flatMap({ case (name, io) =>
        Seq(s"$name:vhdl" -> io, s"$name:verilog" -> io)
      })
      .toMap
    val verilogUnderutilizedCases = Seq(3, 9)
      .map({ denom =>
        val inputs = TestInput(
          basicInputExprs.flatMap(x => (0 until denom).map(_ => Some(x)))
        )
        val outputs = TestOutput(
          basicOutputs.flatMap(x =>
            x +: (0 until (denom - 1)).map(_ => Undefined(U8))
          )
        )
        s"smallconvb2b_1_$denom:verilog" -> (Seq(inputs), outputs)
      })
      .toMap
    val vhdlUnderutilizedCases = Seq(3, 9)
      .map({ denom =>
        val inputs = TestInput(basicInputExprs.map(Some(_)))
        val outputs = TestOutput(basicOutputs)
        s"smallconvb2b_1_$denom:vhdl" -> (Seq(inputs), outputs)
      })
    normalCases ++ verilogUnderutilizedCases ++ vhdlUnderutilizedCases
  }

  private val smallSharpenIO: Map[String, (Seq[TestInput], TestOutput)] = {
    def sharpen1(a: Int, b: Int): Int = {
      val threshold = 15
      val passedThreshold = (a - b > threshold) || (b - a > threshold)
      val h = if (passedThreshold) (b - a) / 4 else 0
      b + h
    }
    def sharpenImage(img: Seq[Seq[Int]]): Seq[Option[Int]] = {
      val blurredImg = conv2d(
        img.map(_.map(Some(_))),
        kernel = Seq(Seq(1, 2, 1), Seq(2, 4, 2), Seq(1, 2, 1)),
        kernelDenom = 1
      ).map(row =>
        // Handle overflow before dividing
        row.map(x => x.map(x => (x % 256) / 16))
      )
      blurredImg.flatten
        .zip(img.flatten)
        .map({
          case (None, _)    => None
          case (Some(a), b) => Some(sharpen1(a, b))
        })
    }
    val basicInputs: Seq[Seq[Int]] =
      (1 to 16).map(_ * 5).grouped(4).toSeq
    val basicInputExprs = basicInputs.flatten.map(C(_)(U8))
    val basicOutputs = sharpenImage(basicInputs).map({
      case Some(x) => C(x)(U8)
      case None    => Undefined(U8)
    })
    val normalCases = Seq(1, 2, 4, 8, 16)
      .map({ par =>
        val (inputs, outputs) = par match {
          case 1 =>
            (
              TestInput(basicInputExprs.map(VecLiteral(_)()).map(Some(_))),
              TestOutput(basicOutputs.map(VecLiteral(_)()))
            )
          case n =>
            assert(n > 1)
            // n valid per cycle
            (
              TestInput(
                basicInputExprs
                  .grouped(n)
                  .map(VecLiteral(_: _*)())
                  .map(Some(_))
                  .toSeq
              ),
              TestOutput(
                basicOutputs
                  .grouped(n)
                  .map(VecLiteral(_: _*)())
                  .toSeq
              )
            )
        }
        s"smallsharpen_$par" -> (Seq(inputs), outputs)
      })
      .flatMap({ case (name, io) =>
        Seq(s"$name:vhdl" -> io, s"$name:verilog" -> io)
      })
      .toMap
    val verilogUnderutilizedCases = Seq(3, 9)
      .map({ denom =>
        val inputs = TestInput(
          basicInputExprs.flatMap(x => (0 until denom).map(_ => Some(x)))
        )
        val outputs = TestOutput(
          basicOutputs.flatMap(x =>
            x +: (0 until (denom - 1)).map(_ => Undefined(U8))
          )
        )
        s"smallsharpen_1_$denom:verilog" -> (Seq(inputs), outputs)
      })
      .toMap
    val vhdlUnderutilizedCases = Seq(3, 9)
      .map({ denom =>
        val inputs = TestInput(basicInputExprs.map(Some(_)))
        val outputs = TestOutput(basicOutputs)
        s"smallsharpen_1_$denom:vhdl" -> (Seq(inputs), outputs)
      })
    normalCases ++ verilogUnderutilizedCases ++ vhdlUnderutilizedCases
  }

  /** Maps benchmark names (e.g., "dot_1_105:vhdl") to inputs and expected
    * outputs.
    *
    * @note
    *   this must be manually updated whenever a new benchmark is added.
    */
  val ioByBenchmark: Map[String, (Seq[TestInput], TestOutput)] = (
    mapIO
      ++ sumIO
      ++ dotIO
      ++ conv1dIO
      ++ smallConv2dIO
      ++ smallConvB2bIO
      ++ smallSharpenIO
  )
}
