package mhir.main.aetherling

import mhir.gen.verilog.{VerilogTestRunner, VerilogTestbenchGenerator}
import mhir.gen.{TestInput, TestPassed}
import mhir.gen.vhdl.{VhdlTestRunner, VhdlTestbenchGenerator}
import mhir.ir._
import mhir.testing.HardwareTest
import org.scalatest.funsuite.AnyFunSuite

/** Tests that the VHDL designs produced by [[mhir.main.aetherling.Compiler]]
  * behave the same as the Verilog designs generated by
  * [[https://dl.acm.org/doi/10.1145/3385412.3385983 Aetherling]].
  */
@HardwareTest
class AetherlingBenchmarkTests extends AnyFunSuite {
  private val AetherlingBenchmarksDir =
    os.pwd / "src" / "test" / "resources" / "aetherling_benchmarks" / "original"
  private val VerilogBenchmarksDir =
    os.pwd / "src" / "test" / "resources" / "aetherling_benchmarks" / "verilog"
  private val VhdlDir = os.pwd / "src" / "test" / "vhdl"
  private val VerilogDir = os.pwd / "src" / "test" / "verilog"

  for (f <- os.list(AetherlingBenchmarksDir)) {
    val benchName = f.baseName

    test(s"$benchName:vhdl:simplified") {
      val (inputs, outputs) = AetherlingBenchmarkTests.ioByBenchmark(benchName)
      val inFile = AetherlingBenchmarksDir / s"$benchName.txt"
      val outDir = VhdlDir / s"aetherling_${benchName}_test"
      if (os.exists(outDir)) os.remove.all(outDir)
      val args = Args(inFile = inFile, outDir = outDir)
      val f = Compiler.compile(args)
      VhdlTestbenchGenerator.makeTestbench(
        inputsByVar = Map(f.asInstanceOf[Function].param -> inputs),
        out = outputs,
        dir = outDir
      )
      assert(VhdlTestRunner.testExistingProject(outDir) == TestPassed)
    }

    test(s"$benchName:vhdl:unsimplified") {
      val (inputs, outputs) = AetherlingBenchmarkTests.ioByBenchmark(benchName)
      val inFile = AetherlingBenchmarksDir / s"$benchName.txt"
      val outDir = VhdlDir / s"aetherling_${benchName}_test"
      if (os.exists(outDir)) os.remove.all(outDir)
      val args = Args(inFile = inFile, outDir = outDir, simplify = false)
      val f = Compiler.compile(args)
      VhdlTestbenchGenerator.makeTestbench(
        inputsByVar = Map(f.asInstanceOf[Function].param -> inputs),
        out = outputs,
        dir = outDir
      )
      assert(VhdlTestRunner.testExistingProject(outDir) == TestPassed)
    }

    test(s"$benchName:verilog") {
      val (inputs, outputs) = AetherlingBenchmarkTests.ioByBenchmark(benchName)
      val projectDir = VerilogDir / s"aetherling_${benchName}_test"
      if (os.exists(projectDir)) os.remove.all(projectDir)
      os.makeDir.all(projectDir)
      os.copy(VerilogBenchmarksDir / s"$benchName.v", projectDir / "Top.v")
      VerilogTestbenchGenerator.makeTestbench(inputs, outputs, projectDir)
      assert(VerilogTestRunner.testExistingProject(projectDir) == TestPassed)
    }
  }
}

object AetherlingBenchmarkTests {

  private val mapIO: Map[String, (TestInput, StmLiteral)] =
    Seq(1, 2, 4, 5, 8, 10, 20, 40, 200)
      .map(par => {
        val flatInputs = (0 until 200).map(i => C(i)(U8))
        val flatOutputs = (0 until 200).map(i => C(i + 5)(U8))
        val (inputs, outputs) = par match {
          case 1 =>
            (
              TestInput(flatInputs.map(e => Some(e))),
              StmLiteral(flatOutputs: _*)()
            )
          case _ =>
            (
              TestInput(
                flatInputs
                  .grouped(par)
                  .map(xs => Some(VecLiteral(xs: _*)()))
                  .toSeq
              ),
              StmLiteral(
                flatOutputs
                  .grouped(par)
                  .map(xs => VecLiteral(xs: _*)())
                  .toSeq: _*
              )()
            )
        }
        s"map_$par" -> (inputs, outputs)
      })
      .toMap

  private val sumIO: Map[String, (TestInput, StmLiteral)] =
    Seq(1, 2, 3, 4, 5, 6, 7, 8)
      .map(par => {
        val flatInputs = (0 until 840).map(i => C(i)(U32))
        val sum = C((0 until 840).sum)(U32)
        val inputs = par match {
          case 1 =>
            TestInput(flatInputs.map(e => Some(e)))
          case _ =>
            TestInput(
              flatInputs
                .grouped(par)
                .map(xs => Some(VecLiteral(xs: _*)()))
                .toSeq
            )
        }
        s"sum_1_${840 / par}" -> (inputs, StmLiteral(sum)())
      })
      .toMap

  /** Maps benchmark names (e.g., "map_1") to inputs and expected outputs.
    *
    * @note
    *   this must be manually updated whenever a new benchmark is added.
    */
  private val ioByBenchmark: Map[String, (TestInput, StmLiteral)] = (
    mapIO
      ++ sumIO
  )
}
