"""
Dataclass for representing compile time reports.
"""

from __future__ import annotations

from csv import DictReader
from dataclasses import dataclass
from pathlib import Path


@dataclass
class CompileTimeReport:
    """
    A breakdown of the duration of each step in compilation.
    """

    parse: int
    """Time taken for parsing."""
    typecheck: int
    """Time taken for type checking."""
    lower: int
    """Time taken for lowering."""
    make_synth: int
    """Time taken for making the expression synthesizable."""
    optimize: int
    """Time taken for optimization."""
    codegen: int
    """Time taken for codegen."""

    @staticmethod
    def extract(p: Path) -> CompileTimeReport:
        """
        Parse the compile time report generated by the compiler in the given .csv file.
        """
        with open(p, "r", encoding="utf-8", newline="") as f:
            reader = DictReader(f)
            parse_time: int | None = None
            typecheck_time: int | None = None
            lower_time: int | None = None
            synth_time: int | None = None
            optim_time: int | None = None
            gen_time: int | None = None
            for row in reader:
                step = row["step"]
                if step == "parse":
                    parse_time = int(row["millis"])
                elif step == "typecheck":
                    typecheck_time = int(row["millis"])
                elif step == "lower":
                    lower_time = int(row["millis"])
                elif step == "make_synth":
                    synth_time = int(row["millis"])
                elif step == "optimize":
                    optim_time = int(row["millis"])
                elif step == "codegen":
                    gen_time = int(row["millis"])
                else:
                    raise ValueError(f"Unknown step: {step}")
            if parse_time is None:
                raise ValueError("Missing time for parsing")
            if typecheck_time is None:
                raise ValueError("Missing time for type checking")
            if lower_time is None:
                raise ValueError("Missing time for lowering")
            if synth_time is None:
                raise ValueError("Missing time for making prog. synthesizable")
            if optim_time is None:
                raise ValueError("Missing time for optimization")
            if gen_time is None:
                raise ValueError("Missing time for codegen")
            return CompileTimeReport(
                parse=parse_time,
                typecheck=typecheck_time,
                lower=lower_time,
                make_synth=synth_time,
                optimize=optim_time,
                codegen=gen_time,
            )
