#!/bin/bash

# Rename all unit tests generated by Aetherling.

set -ue

REPO_ROOT="$(readlink -f "$(dirname "$(readlink -f "$0")")/../../..")"
find "$REPO_ROOT/src/test/resources/aetherling_primitives/original" -name '*.txt' -exec "$REPO_ROOT/src/test/sh/rename_benchmark.sh" {} \;
find "$REPO_ROOT/src/test/resources/aetherling_primitives/verilog"  -name '*.v'   -exec "$REPO_ROOT/src/test/sh/rename_benchmark.sh" {} \;
