#!/usr/bin/env python3

"""
This script generates and synthesizes VHDL and Verilog projects for the given benchmarks.
"""

import os
import subprocess
from argparse import ArgumentParser, Namespace
from pathlib import Path

import lib.constants as c
import lib.list_benchmarks as lb
from lib.optimization_level import OptimizationLevel


def verilog_proj_dir(bench: str) -> Path:
    """
    Find the Verilog project directory for the given benchmark.
    """
    return c.CHISEL_VERILOG_DST_DIR.joinpath(bench)


def generate_verilog(benchmarks: list[str]) -> None:
    """
    Create a Verilog project for each benchmark using the Verilog files generated
    by Aetherling.
    """
    def make_task(bench: str) -> str | None:
        top = c.CHISEL_VERILOG_SRC_DIR.joinpath(f"{bench}.v")
        if not top.is_file():
            print(f"WARNING: missing file {top}")
            return None
        cls = c.VERILOG_PROJ_INITIALIZER
        return f"Test / runMain {cls} {verilog_proj_dir(bench)} {top} --overwrite"
    tasks = [make_task(b) for b in benchmarks]
    tasks = [t for t in tasks if t is not None]
    os.chdir(c.ROOT_DIR)
    if not tasks:
        print("WARNING: no valid projects to generate")
        return
    subprocess.run(["sbt"] + tasks, check=True)


def generate_verilog_testbenches(benchmarks: list[str]) -> None:
    """
    Generate a Verilog testbench for each project generated by Chisel.
    """
    os.chdir(c.ROOT_DIR)
    cls = c.AETHERLING_TESTBENCH_GEN_CLS
    sbt_command = "; ".join([
        f"Test/runMain {cls} {verilog_proj_dir(bench).resolve().as_posix()}"
        for bench in benchmarks
    ])
    subprocess.run(["sbt", sbt_command], check=True)


def vhdl_proj_dir(bench: str) -> Path:
    """
    Find the VHDL project directory for the given benchmark.
    """
    return c.AETHERLING_VHDL_DIR.joinpath(bench)


def generate_vhdl(benchmarks: list[str], recompile_sirop: bool) -> None:
    """
    Call our compiler so as to produce VHDL for each benchmark.
    """
    os.chdir(c.ROOT_DIR)
    if recompile_sirop:
        subprocess.run(["sbt", "assembly"], check=True)
    for bench in benchmarks:
        in_file = c.AETHERLING_SPACETIME_DIR.joinpath(f"{bench}.txt").resolve()
        ctime_file = c.AETHERLING_COMPILE_TIME_DIR.joinpath(f"{bench}.csv").resolve()
        lvl = OptimizationLevel.ALL
        command = [
            "java", "-jar", c.JAR_PATH.as_posix(),
            "-s", "aetherling", "-i", in_file.as_posix(),
            "--out:vhdl", vhdl_proj_dir(bench).as_posix(), "--overwrite",
            "--out:vhdl:family", "Arria 10",
            "--out:vhdl:device", "10AX115N2F40E2LG",
            "--out:pp", "-",
            "--out:ctime", ctime_file.as_posix(),
        ] + lvl.flags.split()
        command = [x for x in command if x]
        print()
        print(f"Running : {' '.join(command)}")
        subprocess.run(command, check=True)


def generate_vhdl_testbenches(benchmarks: list[str]) -> None:
    """
    Generate a VHDL testbench for each project generated by the Sirop compiler.
    """
    os.chdir(c.ROOT_DIR)
    cls = c.AETHERLING_TESTBENCH_GEN_CLS
    sbt_command = "; ".join([
        f"Test/runMain {cls} {vhdl_proj_dir(bench).resolve().as_posix()}"
        for bench in benchmarks
    ])
    subprocess.run(["sbt", sbt_command], check=True)


def main(
    benchmarks: list[str],
    skip_chisel: bool,
    skip_sirop: bool,
    recompile_sirop: bool,
) -> None:
    """
    Script entry point
    """
    print("-" * 80)
    print("- Generating projects with Chisel and Sirop...")
    print(f"- Benchmarks : {', '.join(benchmarks)}")
    print("-" * 80)

    if not skip_chisel:
        c.CHISEL_VERILOG_DST_DIR.mkdir(exist_ok=True, parents=True)
        print("Generating Verilog...")
        generate_verilog(benchmarks)
        generate_verilog_testbenches(benchmarks)

    if not skip_sirop:
        c.AETHERLING_VHDL_DIR.mkdir(exist_ok=True, parents=True)
        c.AETHERLING_COMPILE_TIME_DIR.mkdir(exist_ok=True, parents=True)
        print("Generating VHDL...")
        generate_vhdl(benchmarks, recompile_sirop=recompile_sirop)
        generate_vhdl_testbenches(benchmarks)

    print()


def parse_args() -> Namespace:
    """
    Parse the command line arguments.
    """
    parser = ArgumentParser(description="Generates and synthesizes the given benchmarks.")
    parser.add_argument(
        "benchmarks",
        nargs="*",
        help=(
            "the benchmarks to process"
            f" (the ones in the paper can be selected by {lb.ACTIVE_BENCH_GLOB})"
        ),
    )
    parser.add_argument(
        "--skip-chisel",
        action="store_true",
        help="don't generate any Verilog code with Chisel"
    )
    parser.add_argument(
        "--skip-sirop",
        action="store_true",
        help="don't generate any VHDL code with Sirop"
    )
    parser.add_argument(
        "--recompile-sirop",
        action="store_true",
        help="run 'sbt assembly' before invoking the Sirop compiler",
    )
    args = parser.parse_args()
    args.benchmarks = lb.names_from_args(args.benchmarks)
    return args


if __name__ == "__main__":
    _args = parse_args()
    main(
        benchmarks=_args.benchmarks,
        skip_chisel=_args.skip_chisel,
        skip_sirop=_args.skip_sirop,
        recompile_sirop=_args.recompile_sirop,
    )
