#!/usr/bin/env python3

"""
This script generates VHDL projects for the given SHIR benchmarks.
"""

import os
import shutil
import subprocess
from argparse import ArgumentParser, Namespace

import lib.constants as c


def generate_shir(prog: str) -> None:
    """
    Generate VHDL project from the files generated by SHIR.
    """
    print(f"Generating VHDL for {prog} (SHIR)...")
    cwd = os.getcwd()
    os.chdir(c.SHIR_SUBMODULE_DIR)
    try:
        subprocess.run(["sbt", f"testOnly *SiropBenches -- *{prog}* "], check=True)
    finally:
        os.chdir(cwd)
    in_dir = c.SHIR_SUBMODULE_DIR.joinpath("out", prog)
    out_dir = c.SHIR_VHDL_DIR.joinpath(prog)
    shutil.rmtree(out_dir, ignore_errors=True)
    os.chdir(c.SHIR_VHDL_DIR)
    # Files generated by SHIR
    out_dir.mkdir(exist_ok=False, parents=True)
    shutil.copytree(src=in_dir, dst=out_dir.joinpath("design"))
    # Testbench (if applicable)
    testbench = c.SHIR_TESTBENCHES_DIR.joinpath(f"{prog}_test.vhd")
    if testbench.is_file():
        out_dir.joinpath("test").mkdir()
        shutil.copy(src=testbench, dst=out_dir.joinpath("test", "test_top.vhd"))
        shutil.copy(src=c.TEST_VHDL_SH, dst=out_dir.joinpath("test_vhdl.sh"))
    else:
        print(f"  WARNING: no testbench found for {prog}")
        print(f"  ({testbench} does not exist or is not a file)")
    # Testbench expected outputs (if applicable)
    outputs = c.SHIR_TESTBENCHES_DIR.joinpath(f"{prog}_outputs.txt")
    if outputs.is_file():
        out_dir.joinpath("test").mkdir(exist_ok=True)
        shutil.copy(src=outputs, dst=out_dir.joinpath("test", "outputs.txt"))
    # Compilation settings
    shutil.copy(src=c.DEFAULT_QPF, dst=out_dir.joinpath("top.qpf"))
    shutil.copy(src=c.DEFAULT_QSF, dst=out_dir.joinpath("top.qsf"))
    shutil.copy(src=c.DEFAULT_SDC, dst=out_dir.joinpath("top.sdc"))
    names = [p.name for p in out_dir.joinpath("design").iterdir()]
    assignments = [f"set_global_assignment -name VHDL_FILE design/{name}\n" for name in names]
    with open(out_dir.joinpath("top.qsf"), mode="a", encoding="utf-8") as f:
        f.write("".join(assignments))


def main(programs: list[str]) -> None:
    """
    Script entry point.
    """
    print("-" * 80)
    print("- Generating projects...")
    print(f"- Programs : {', '.join(programs)}")
    print("-" * 80)


    c.SHIR_VHDL_DIR.mkdir(exist_ok=True, parents=True)

    for prog in programs:
        generate_shir(prog)


def parse_args() -> Namespace:
    """
    Parse the command-line arguments.
    """
    parser = ArgumentParser(
        description="generates VHDL projects for the given SHIR benchmarks."
    )
    parser.add_argument(
        "programs",
        nargs="*",
        help=(
            "the names of the programs to process"
            f" (the ones in the paper are: {' '.join(c.ACTIVE_BENCHES)})"
        )
    )
    args = parser.parse_args()
    if not args.programs:
        args.programs = c.ACTIVE_BENCHES
    return args


if __name__ == "__main__":
    _args = parse_args()
    main(_args.programs)
