#!/bin/python3

"""
This script generates VHDL projects for the given SHIR benchmarks.
"""

import os
import shutil
import subprocess
from argparse import ArgumentParser, Namespace

import lib.constants as c
from lib.optimization_level import OptimizationLevel


def generate_shir(prog: str) -> None:
    """
    Generate VHDL project from the files generated by SHIR.
    """
    print(f"Generating VHDL for {prog} (SHIR)...")
    in_dir = c.SHIR_ORIGINALS_DIR.joinpath(prog)
    out_dir = c.SHIR_VHDL_DIR.joinpath(prog)
    shutil.rmtree(out_dir, ignore_errors=True)
    # Files generated by SHIR
    shutil.copytree(src=in_dir, dst=out_dir)
    # Manual patch files (e.g., to minimize the resource usage of the inputs)
    patch_dir = c.SHIR_ORIGINALS_DIR.joinpath(f"{prog}_patch")
    for p in patch_dir.iterdir():
        shutil.copy(src=p, dst=out_dir.joinpath(p.name))
    # Compilation settings
    shutil.copy(src=c.DEFAULT_QPF, dst=out_dir.joinpath("top.qpf"))
    shutil.copy(src=c.DEFAULT_QSF, dst=out_dir.joinpath("top.qsf"))
    shutil.copy(src=c.DEFAULT_SDC, dst=out_dir.joinpath("top.sdc"))
    # Compilation settings for inputs
    input_components = [
        line.strip()
        for line in patch_dir.joinpath("inputs.txt").read_text().split("\n")
        if line.strip()
    ]
    for component in input_components:
        shutil.copy(src=c.DEFAULT_SDC, dst=out_dir.joinpath(f"{component}.sdc"))
        settings = (
            c.DEFAULT_QSF.read_text()
                .replace(
                    f"set_global_assignment -name PROJECT_OUTPUT_DIRECTORY output_files",
                    f"set_global_assignment -name PROJECT_OUTPUT_DIRECTORY output_files_{component}",
                )
                .replace(
                    f"set_global_assignment -name TOP_LEVEL_ENTITY top",
                    f"set_global_assignment -name TOP_LEVEL_ENTITY {component}",
                )
        )
        out_dir.joinpath(f"{component}.qsf").write_text(settings)


def main(programs: list[str]) -> None:
    """
    Script entry point.
    """
    print("-" * 80)
    print("- Generating projects...")
    print(f"- Programs : {', '.join(programs)}")
    print("-" * 80)

    c.SHIR_VHDL_DIR.mkdir(exist_ok=True, parents=True)

    for prog in programs:
        generate_shir(prog)


def parse_args() -> Namespace:
    """
    Parse the command-line arguments.
    """
    parser = ArgumentParser(
        description="generates VHDL projects for the given SHIR benchmarks."
    )
    parser.add_argument(
        "programs",
        nargs="*",
        help="the names of the programs to process"
    )
    return parser.parse_args()


if __name__ == "__main__":
    _args = parse_args()
    main(_args.programs)
