#!/usr/bin/env python3

"""
This script generates VHDL projects via Sirop for the given benchmarks.
"""

import os
import subprocess
from argparse import ArgumentParser, Namespace
from pathlib import Path

import lib.constants as c
from lib.optimization_level import OptimizationLevel


def proj_dir(prog: str) -> Path:
    """
    Find the VHDL project directory for the given benchmark.
    """
    return c.SIROP_VHDL_DIR.joinpath(prog)


def generate_design(prog: str) -> None:
    """
    Generate VHDL project using our compiler.
    """
    print(f"Generating VHDL design for {prog} (Sirop)...")
    ctime_file = c.SIROP_COMPILE_TIME_DIR.joinpath(f"{prog}.csv")
    lvl = OptimizationLevel.ALL
    command = [
        "java", "-jar", c.JAR_PATH.as_posix(),
        "-s", "stored", "-i", f"shir:{prog}",
        "--out:vhdl", proj_dir(prog).as_posix(), "--overwrite",
        "--out:vhdl:family", "Arria 10",
        "--out:vhdl:device", "10AX115N2F40E2LG",
        "--out:pp", "-",
        "--out:ctime", ctime_file.as_posix(),
    ] + lvl.flags.split()
    command = [x for x in command if x]
    print()
    print(f"Running : {' '.join(command)}")
    subprocess.run(command, check=True)


def generate_testbench(prog: str) -> None:
    """
    Generate a VHDL testbench for the project generated by the Sirop compiler.
    """
    out_dir = proj_dir(prog)
    os.chdir(c.ROOT_DIR)
    sbt_command = f"Test/runMain {c.STORED_TESTBENCH_GEN_CLS} {out_dir.resolve().as_posix()}"
    subprocess.run(["sbt", sbt_command], check=True)


def main(
    programs: list[str],
    recompile_sirop: bool,
) -> None:
    """
    Script entry point.
    """
    print("-" * 80)
    print("- Generating projects...")
    print(f"- Programs : {', '.join(programs)}")
    print("-" * 80)


    c.SIROP_VHDL_DIR.mkdir(exist_ok=True, parents=True)
    c.SIROP_COMPILE_TIME_DIR.mkdir(exist_ok=True, parents=True)

    os.chdir(c.ROOT_DIR)
    if recompile_sirop:
        subprocess.run(["sbt", "assembly"], check=True)
    for prog in programs:
        generate_design(prog)
        generate_testbench(prog)


def parse_args() -> Namespace:
    """
    Parse the command-line arguments.
    """
    parser = ArgumentParser(
        description="generates VHDL projects via Sirop for the given benchmarks."
    )
    parser.add_argument(
        "--recompile-sirop",
        action="store_true",
        help="run 'sbt assembly' before invoking the Sirop compiler",
    )
    parser.add_argument(
        "programs",
        nargs="*",
        help=(
            "the names of the programs to process"
            f" (the ones in the paper are: {' '.join(c.ACTIVE_BENCHES)})"
        )
    )
    args = parser.parse_args()
    if not args.programs:
        args.programs = c.ACTIVE_BENCHES
    return args


if __name__ == "__main__":
    _args = parse_args()
    main(
        _args.programs,
        recompile_sirop=_args.recompile_sirop,
    )
