"""
Functions for testing the VHDL output generated by the Sirop compiler.
"""

from pathlib import Path
import subprocess

import constants as c


def is_used_for_vhdl_test(p: Path) -> bool:
    """
    Check whether the given file is used for the VHDL tests.
    """
    if (
        p.name.endswith(".vhdl.tree.txt")
        and p.with_suffix("").with_suffix("").with_suffix(".sirop").is_file()
    ):
        return True
    if (
        p.name.endswith(".vhdl.interface.txt")
        and p.with_suffix("").with_suffix("").with_suffix(".sirop").is_file()
    ):
        return True
    return False


def vhdl_test_exists(src: Path) -> bool:
    """
    Check whether there are any files describing expected outputs for VHDL.
    """
    if src.with_suffix(".vhdl.tree.txt").is_file():
        return True
    if src.with_suffix(".vhdl.interface.txt").is_file():
        return True
    return False


def test_vhdl(src: Path) -> bool:
    """
    Test that the VHDL code looks OK (files generated, interface of the top-level entity).
    """
    name = src.with_suffix("").relative_to(c.RESOURCES).as_posix()
    print(f"{name} (VHDL) ... ", end="", flush=True)
    vhdl_dir = c.ACTUAL_OUTPUTS / name
    result = subprocess.run(
        [
            "java", "-jar", c.JAR.as_posix(),
            "-i", src.as_posix(),
            "--out:vhdl", vhdl_dir.as_posix(),
            "--overwrite",
            "--quiet",
        ],
        check=False,
        capture_output=True,
    )
    # Check error code
    expected_code = 1 if src.parent.name.endswith("Error") else 0
    if result.returncode != expected_code:
        print(f"WRONG STATUS (expected {expected_code} but got {result.returncode})")
        return False
    # Check file tree (if applicable)
    expected_tree_path = src.with_suffix(".vhdl.tree.txt")
    if expected_tree_path.is_file():
        expected_tree = expected_tree_path.read_text(encoding="utf-8")
        actual_tree = _get_tree(vhdl_dir)
        actual_out_file = c.ACTUAL_OUTPUTS / f"{name}.vhdl.tree.txt"
        actual_out_file.write_text(actual_tree, encoding="utf-8")
        if actual_tree != expected_tree:
            print(
                f"WRONG FILE STRUCTURE (compare {expected_tree_path.relative_to(c.ROOT)}"
                f" with {actual_out_file.relative_to(c.ROOT)})"
            )
            return False
    # Check entity interface (if applicable)
    expected_interface_path = src.with_suffix(".vhdl.interface.txt")
    if expected_interface_path.is_file():
        expected_interface = expected_interface_path.read_text(encoding="utf-8")
        actual_interface = _get_interface(vhdl_dir)
        actual_out_file = c.ACTUAL_OUTPUTS / f"{name}.vhdl.interface.txt"
        actual_out_file.write_text(actual_interface, encoding="utf-8")
        if actual_interface != expected_interface:
            print(
                f"WRONG INTERFACE (compare {expected_interface_path.relative_to(c.ROOT)}"
                f" with {actual_out_file.relative_to(c.ROOT)})"
            )
            return False
    print("OK")
    return True


def _get_tree(vhdl_dir: Path) -> str:
    """
    Get the output of the `tree` command for the given path.
    """
    result = subprocess.run(
        ["tree", vhdl_dir.resolve().as_posix()],
        check=True,
        encoding="utf-8",
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
    )
    return result.stdout


def _get_interface(vhdl_dir: Path) -> str:
    """
    Get the top-level entity declaration from the given VHDL project.
    """
    qsf_files = list(vhdl_dir.glob("*.qsf"))
    if not qsf_files:
        return f"ERROR: no .qsf files found in {vhdl_dir}"
    if len(qsf_files) > 1:
        return f"ERROR: {len(qsf_files)} .qsf files found in {vhdl_dir}"
    qsf_file = qsf_files[0]
    top_name = qsf_file.stem
    vhd_file = vhdl_dir.joinpath("design", f"{top_name}.vhd")
    if not vhd_file.is_file():
        return f"ERROR: missing top-level .vhd file {vhd_file}"
    output = []
    inside_entity = False
    with open(vhd_file, "r", encoding="utf-8") as f:
        for line in f:
            line = line.rstrip()
            if line == f"entity {top_name} is":
                assert not output
                inside_entity = True
            if inside_entity:
                output.append(line)
            if line == f"end entity {top_name};":
                break
    return "".join([f"{line}\n" for line in output])
